
DECLARE

    vBATCH_NO VARCHAR2(30):=10568;
    vREQ_ID NUMBER:=1228;

    vPROD_ID NUMBER:=132;
    vMFG_DATE VARCHAR2(20):='03-DEC-2022';
    vEXP_DATE VARCHAR2(20);
    vSHELF_LIFE NUMBER;
    
    vCNT     NUMBER;


BEGIN

    SELECT COUNT(*) INTO vCNT FROM MM_INT_REQ_MST
    WHERE FOR_BATCHES=vBATCH_NO
    AND ID <> vREQ_ID;
    
    IF vCNT = 0 THEN
    

        SELECT LAST_DAY(TO_DATE(vMFG_DATE,'DD-MM-RRRR')+(SHELF_LIFE*30)) INTO vEXP_DATE--SHELF_LIFE INTO vSHELF_LIFE 
        FROM ADM_PRODUCTS
        WHERE ID=vPROD_ID;

        --SELECT LAST_DAY(TO_DATE(vMFG_DATE,'DD-MM-RRRR')+(vSHELF_LIFE*30)) INTO vEXP_DATE FROM DUAL;
        
    
    END IF;

    DBMS_OUTPUT.PUT_LINE('PROD_ID-> '||vPROD_ID||',MFG_D-> '||vMFG_DATE||',SH_LIF->'||vSHELF_LIFE||',EXP_D->'||vEXP_DATE );

END;


    SELECT TRUNC(REQ_DATE) MFG_DATE,LAST_DAY(TO_DATE(TRUNC(REQ_DATE),'DD/MM/RRRR')+(AP.SHELF_LIFE*30)) EXP_DATE 
      FROM MM_INT_REQ_MST MIRM,ADM_PRODUCTS AP
     WHERE MIRM.FOR_PRODUCTS = AP.ID
       AND MIRM.ID = 1228
       AND MIRM.SBU_ID=2
       AND MIRM.STATUS=1
    

    SELECT LAST_DAY(TO_DATE(vMFG_DATE,'DD-MM-RRRR')+(SHELF_LIFE*30)) INTO vEXP_DATE--SHELF_LIFE INTO vSHELF_LIFE 
    FROM ADM_PRODUCTS
    WHERE ID=132;

select * from PP_PRODUCT_BATCH
where id=10568;

MFG_DATE,EXP_DATE,BATCH_STATUS,BATCH_START_DATE

select * from adm_code_elements
where code_id=719