


--5.-PLANT NAME LIST

SELECT ID,PLANT_NAME FROM ADM_PLANT
WHERE PLANT_TYPE=183
AND LVL=3
AND SBU_ID = :pSBU_ID;

--6.-PRODUCTION LINE LIST

SELECT ID,PLANT_NAME FROM ADM_PLANT
WHERE PARENT = :pPLANT_ID --()
AND PLANT_TYPE=183 AND LVL=4
AND SBU_ID = :pSBU_ID;



--7--BATCH LIST

SELECT PPB.ID,PPB.BATCH_NO,PPB.PROD_ID,AP.PROD_NAME 
FROM PP_PRODUCT_BATCH PPB
LEFT JOIN ADM_PRODUCTS AP ON AP.ID = PPB.PROD_ID
LEFT JOIN PP_PROD_LINE_CATEGORY PPLC ON PPLC.PROD_CAT_ID = AP.PROD_SUB_CAT_ID
WHERE PPLC.PROD_LINE_ID = :pPROD_LINE_ID --()
AND PPB.IS_TRANSFERED = 'N'
AND PPB.TRANSFER_ID IS NULL
AND NVL(PPB.TRANSFER_QTY,0) = 0
AND PPB.SBU_ID = :pSBU_ID
AND PPB.BATCH_STATUS IN (SELECT ID FROM ADM_CODE_ELEMENTS
                         WHERE CODE_KEY='BATCH_STATUS'
                         AND ELEMENT_KEY IN ('EC719-02','EC719-03','EC719-04')
                        );


--8--PROCESS AND SUB-PROCESS
WITH Q AS (
SELECT PPTP.PROCESS_ID,PPC.PROCESS_NAME,PPTP.SUB_PROCESS_ID,PPC1.PROCESS_NAME SUB_PROCESS
FROM PP_PROC_TYPE_PROCESS PPTP
LEFT JOIN PP_PROD_PROC_TYPE PPPT ON PPPT.ID = PPTP.PROD_PROC_TYPE_ID
LEFT JOIN PP_PROCESS_CONFIG PPC ON PPC.ID = PPTP.PROCESS_ID
LEFT JOIN PP_PROCESS_CONFIG PPC1 ON PPC1.ID = PPTP.SUB_PROCESS_ID
WHERE PPPT.PROD_ID = :pPROD_ID
AND PPPT.SBU_ID = :pSBU_ID
ORDER BY PROCESS_SEQUENCE) 
SELECT JSON_ARRAYAGG(
       JSON_OBJECT(
                   'process_id'   VALUE A.PROCESS_ID,
                   'process_name' VALUE A.PROCESS_NAME,
                   'sub_process'  VALUE (
                    SELECT JSON_ARRAYAGG(
                    JSON_OBJECT(
                                'sub_process_id' VALUE B.SUB_PROCESS_ID,
                                'sub_process_name' VALUE B.SUB_PROCESS
                    )--2ND OBJECT END
                    ) FROM (SELECT * FROM Q WHERE PROCESS_ID=A.PROCESS_ID) B --2ND ARRAY END
                   ) --END sub_process
       )--1ST OBJECT END
)  FROM (SELECT * FROM Q) A; --1ST ARRAY END


--9--OPERATOR LIST
SELECT HE.ID,HE.EMP_ID,HE.EMP_NAME,HD.DESIG_NAME,HDE.DEPARTMENT_NAME 
FROM PP_PROD_ROOM_MAN PPRM
LEFT JOIN ADM_PLANT AP ON AP.ID = PPRM.ROOM_ID
LEFT JOIN HRM_EMPLOYEE HE ON HE.ID = PPRM.EMP_ID
LEFT JOIN HRM_DESIGNATION HD ON HE.DESIGNATION_ID=HD.ID
LEFT JOIN HRM_DEPARTMENT HDE ON HE.DEPARTMENT_ID=HDE.ID
WHERE AP.PARENT=:pPLANT_LINE_ID
AND  PPRM.SBU_ID = :pSBU_ID
AND HE.DESIGNATION_ID IS NOT NULL
AND HE.DEPARTMENT_ID IS NOT NULL;

--10--ROOM LIST

SELECT ID,PLANT_NAME AS ROOM_NAME FROM ADM_PLANT
WHERE PARENT = :pPLANT_LINE_ID --()
AND SBU_ID  = :pSBU_ID;


--11--MACHINE LIST

SELECT PPRM.MACHINE_ID,FAR.ASSET_NAME AS MACHINE_NAME
FROM PP_PROD_ROOM_MACHINE PPRM
LEFT JOIN FICO_ASSET_REGISTER FAR ON FAR.ID = PPRM.MACHINE_ID
WHERE ROOM_ID = :pROOM_ID
AND PPRM.SBU_ID = :pSBU_ID;

--12--MOLD LIST

SELECT PPRM.MOLD_ID,PMM.MOLD_NAME FROM PP_PROD_ROOM_MOLD PPRM
LEFT JOIN PP_MOLD_MST PMM ON PMM.ID = PPRM.MOLD_ID
WHERE ROOM_MACHINE_ID = :pROOM_MACHINE_ID;

--1--LEFT SIDE MST DATA INFO

SELECT PPLA.ID,ASSIGN_DATE, PLANT_ID,APPI.PLANT_NAME,PRODUCTION_LINE_ID,APPLI.PLANT_NAME
FROM PP_PROD_LINE_ALLO PPLA
LEFT JOIN ADM_PLANT APPI ON APPI.ID = PPLA.PLANT_ID
LEFT JOIN ADM_PLANT APPLI ON APPLI.ID = PPLA.PRODUCTION_LINE_ID
WHERE PPLA.SBU_ID = :pSBU_ID;

--2

SELECT * FROM PP_PROD_LINE_BATCH PPLB
WHERE PROD_LINE_ID = :pPROD_LINE_ID;

--3--OPERATORS DATA SHOW AFTER SAVE

SELECT PPLM.ID, LINE_BATCH_ID,PPLM.PERSON_ID,HE.EMP_NAME,HD.DESIG_NAME,HDE.DEPARTMENT_NAME , EXP_LEVEL 
FROM PP_PROD_LINE_MAN PPLM
LEFT JOIN HRM_EMPLOYEE HE ON HE.ID = PPLM.PERSON_ID
LEFT JOIN HRM_DESIGNATION HD ON HE.DESIGNATION_ID=HD.ID
LEFT JOIN HRM_DEPARTMENT HDE ON HE.DEPARTMENT_ID=HDE.ID
WHERE PPLM.LINE_BATCH_ID = :pLINE_BATCH_ID;


--4--MACHINE DATA SHOW AFTER SAVE

SELECT PPLR.ID,LINE_BATCH_ID,ROOM_ID,AP.PLANT_NAME, MACHINE_ID,FAR.ASSET_NAME AS MACHINE_NAME, MOLD_ID,PMM.MOLD_NAME, STD_TIME 
FROM PP_PROD_LINE_ROOM PPLR
LEFT JOIN ADM_PLANT AP ON AP.ID = PPLR.ROOM_ID
LEFT JOIN PP_MOLD_MST PMM ON PMM.ID = PPLR.MOLD_ID
LEFT JOIN FICO_ASSET_REGISTER FAR ON FAR.ID = PPLR.MACHINE_ID
WHERE PPLR.LINE_BATCH_ID = :pLINE_BATCH_ID;


--10 ALL EMPLOYEE

SELECT HE.EMP_ID, HE.EMP_NAME, HD.DESIG_NAME, HDE.DEPARTMENT_NAME 
FROM HRM_EMPLOYEE HE 
JOIN HRM_DESIGNATION HD ON HE.DESIGNATION_ID=HD.ID
JOIN HRM_DEPARTMENT HDE ON HE.DEPARTMENT_ID=HDE.ID
WHERE  HE.DESIGNATION_ID IS NOT NULL
AND HE.DEPARTMENT_ID IS NOT NULL;