SELECT AP.ID, AP.PARENT, AP.PROD_TYPE, AP.PROD_CAT, AP.PROD_GROUP, AP.PROD_NAME, AP.PROD_CODE, AP.COM_PACK_SIZE, AP.COM_UOM, AC.ELEMENT_NAME,
        CASE WHEN ASP.IS_PROMO_PROD = 'N' AND AP.PROD_TYPE=501 THEN 'COMMERCIAL'
                        WHEN ASP.IS_PROMO_PROD = 'Y'  AND AP.PROD_TYPE=501 THEN 'SAMPLE'
                        WHEN ASP.IS_PROMO_PROD = 'E'  AND AP.PROD_TYPE=501 THEN SSA.AREA_NAME 
                        WHEN AP.PROD_TYPE=514 THEN 'BULK'
                        WHEN AP.PROD_TYPE=504 THEN 'SFG' END PROD_TYPE_DESC
FROM ADM_PRODUCTS AP JOIN ADM_SBU_PRODUCTS ASP ON AP.ID=ASP.PROD_ID
LEFT JOIN ADM_CODE_ELEMENTS AC ON AP.COM_UOM=AC.ID
LEFT JOIN SD_SALES_AREA SSA ON SSA.ID = ASP.EXPORT_TERRITORY
WHERE AP.PROD_TYPE IN(501,506,504,514)
CONNECT BY PRIOR  AP.ID = AP.PARENT START WITH AP.PARENT is null
