
SELECT * FROM GET_BATCH_DOC_REQ_QTY_CHK_LIST(200, 2, 10052);

SELECT PBD.MAT_PROD_ID,ASP.DISPLAY_NAME, NVL(BATCH_QTY,0) BATCH_QTY, UOM,NVL(BATCH_QTY,0)*NVL(:pNO_OF_BATCH,1) REQUIRED_QTY,
JERP_INVENTORY_UTIL.AVAILABLE_QUANTITY(JERP_INVENTORY_UTIL.GET_STORE(DECODE (JERP_PP_UTIL.FD_GET_MATERIAL_CODE(PBD.MAT_PROD_ID), 'RM', 205, 'PM', 206),'OUT'), PBD.MAT_PROD_ID) AVAILABLE_QTY,
ACE.ELEMENT_NAME
FROM PP_BOM_DTL PBD
LEFT JOIN PP_BOM_MST PBM ON PBM.ID = PBD.BOM_ID
LEFT JOIN ADM_SBU_PRODUCTS ASP ON ASP.PROD_ID = PBD.MAT_PROD_ID
LEFT JOIN ADM_CODE_ELEMENTS ACE ON  ACE.ID=PBD.UOM
WHERE PBM.MAT_PROD_ID=:pPROD_ID
AND ( (:pDOC_TYPE = '10050' AND IS_BMR ='Y')
OR (:pDOC_TYPE = '10051' AND IS_BMR ='N')
OR (:pDOC_TYPE = '10052' AND IS_BMR IN ('Y','N'))
);