--all fg
select * FROM ADM_PRODUCTS WHERE PROD_TYPE=501

--all rm
select * FROM ADM_PRODUCTS WHERE PROD_TYPE=502

--all pm
select * FROM ADM_PRODUCTS WHERE PROD_TYPE=503

--all sfg
select * FROM ADM_PRODUCTS WHERE PROD_TYPE=504

--all bulk
select * FROM ADM_PRODUCTS WHERE PROD_TYPE=514


--all master code
select * FROM ADM_PRODUCTS WHERE PROD_TYPE=506

select * FROM ADM_sbu_PRODUCTS WHERE is_promo_prod='M'

--------------

--ALL PRODUCT CODE RELATED TO A MASTER CODE
SELECT AP.ID, AP.PARENT, AP.PROD_TYPE, AP.PROD_CAT, AP.PROD_GROUP, AP.PROD_NAME, AP.PROD_CODE, AP.COM_PACK_SIZE, AP.COM_UOM, AC.ELEMENT_NAME,
        CASE WHEN ASP.IS_PROMO_PROD = 'N' AND AP.PROD_TYPE=501 THEN 'COMMERCIAL'
                        WHEN ASP.IS_PROMO_PROD = 'Y'  AND AP.PROD_TYPE=501 THEN 'SAMPLE'
                        WHEN ASP.IS_PROMO_PROD = 'E'  AND AP.PROD_TYPE=501 THEN SSA.AREA_NAME 
                        WHEN AP.PROD_TYPE=504 THEN 'BULK'
                        WHEN AP.PROD_TYPE=514 THEN 'SFG' END PROD_TYPE_DESC
FROM ADM_PRODUCTS AP JOIN ADM_SBU_PRODUCTS ASP ON AP.ID=ASP.PROD_ID
LEFT JOIN ADM_CODE_ELEMENTS AC ON AP.COM_UOM=AC.ID
LEFT JOIN SD_SALES_AREA SSA ON SSA.ID = ASP.EXPORT_TERRITORY
WHERE AP.PROD_TYPE IN(501,506,504,514)
AND (AP.ID=272 OR AP.PARENT=272)
CONNECT BY PRIOR  AP.ID = AP.PARENT START WITH AP.PARENT IS NULL

-------------
SELECT ASP.PROD_ID,ASP.DISPLAY_NAME, ASP.DISPLAY_CODE, ASP.IS_PROMO_PROD, AP.PROD_TYPE, ASP.PARENT_PROD_ID, PAR.DISPLAY_NAME PARENT_PROD_NAME, PAR.DISPLAY_CODE PARENT_DISPLAY_CODE
FROM ADM_SBU_PRODUCTS ASP JOIN ADM_PRODUCTS AP ON ASP.PROD_ID=AP.ID
JOIN (
    SELECT ASP.PROD_ID,ASP.DISPLAY_NAME, ASP.DISPLAY_CODE
        FROM ADM_SBU_PRODUCTS ASP JOIN ADM_PRODUCTS AP ON ASP.PROD_ID=AP.ID
        WHERE SBU_ID=2 AND ASP.IS_PROMO_PROD='M' AND AP.PROD_TYPE=506 and ASP.PROD_ID= :pMST_PROD_ID--272
    ) PAR ON ASP.PARENT_PROD_ID=PAR.PROD_ID
WHERE SBU_ID=2 --AND (ASP.IS_PROMO_PROD='N' OR ASP.IS_PROMO_PROD='E' OR ASP.IS_PROMO_PROD='Y')
AND AP.PROD_TYPE=501
ORDER BY ASP.DISPLAY_NAME



SELECT  AP.ID PRODUCT_ID, AP.PROD_NAME, FD_GET_BASE_UOM(ASP.BASE_UOM) PROD_UOM, AP.COM_PACK_SIZE,  AP.OLD_CODE,
        CASE WHEN ASP.IS_PROMO_PROD = 'N' THEN 'COMMERCIAL' 
             WHEN ASP.IS_PROMO_PROD = 'Y' THEN 'SAMPLE'
             WHEN ASP.IS_PROMO_PROD = 'E' THEN SSA.AREA_NAME END PROD_TYPE
FROM ADM_PRODUCTS AP,  ADM_SBU_PRODUCTS ASP
     LEFT JOIN SD_SALES_AREA SSA ON SSA.ID = ASP.EXPORT_TERRITORY
WHERE AP.ID = ASP.PROD_ID
AND AP.PROD_TYPE = 501
AND AP.PARENT = 101
AND AP.STATUS = 1

-----

SELECT A.PROD_ID,B.PROD_NAME, A.DISPLAY_CODE,PROD_UOM, B.COM_PACK_SIZE, A.IS_PROMO_PROD, 
A.PROD_TYPE,B.PROD_TYPE_DESC, A.PARENT_PROD_ID,A.PARENT_PROD_NAME, A.PARENT_DISPLAY_CODE,B.OLD_CODE
FROM (
SELECT ASP.PROD_ID,ASP.DISPLAY_NAME, ASP.DISPLAY_CODE, ASP.IS_PROMO_PROD, AP.PROD_TYPE, ASP.PARENT_PROD_ID, PAR.DISPLAY_NAME PARENT_PROD_NAME, PAR.DISPLAY_CODE PARENT_DISPLAY_CODE
FROM ADM_SBU_PRODUCTS ASP JOIN ADM_PRODUCTS AP ON ASP.PROD_ID=AP.ID
JOIN (
    SELECT ASP.PROD_ID,ASP.DISPLAY_NAME, ASP.DISPLAY_CODE
        FROM ADM_SBU_PRODUCTS ASP JOIN ADM_PRODUCTS AP ON ASP.PROD_ID=AP.ID
        WHERE SBU_ID=2 AND ASP.IS_PROMO_PROD='M' AND AP.PROD_TYPE=506 and ASP.PROD_ID=101
    ) PAR ON ASP.PARENT_PROD_ID=PAR.PROD_ID
WHERE SBU_ID=2 --AND (ASP.IS_PROMO_PROD='N' OR ASP.IS_PROMO_PROD='E' OR ASP.IS_PROMO_PROD='Y')
AND AP.PROD_TYPE=501
ORDER BY ASP.DISPLAY_NAME)A,(
SELECT  AP.ID PRODUCT_ID, AP.PROD_NAME, FD_GET_BASE_UOM(ASP.BASE_UOM) PROD_UOM, AP.COM_PACK_SIZE,  AP.OLD_CODE,
        CASE WHEN ASP.IS_PROMO_PROD = 'N' THEN 'COMMERCIAL' 
             WHEN ASP.IS_PROMO_PROD = 'Y' THEN 'SAMPLE'
             WHEN ASP.IS_PROMO_PROD = 'E' THEN SSA.AREA_NAME END PROD_TYPE_DESC
FROM ADM_PRODUCTS AP,  ADM_SBU_PRODUCTS ASP
     LEFT JOIN SD_SALES_AREA SSA ON SSA.ID = ASP.EXPORT_TERRITORY
WHERE AP.ID = ASP.PROD_ID
AND AP.PROD_TYPE = 501
AND AP.PARENT = 101
AND AP.STATUS = 1)B
WHERE A.PROD_ID=B.PRODUCT_ID