
API TYPE : GET
API NAME : api/pp/get-qc-test-name/{pPROD_TYPE}

Response Fields :  ID, TEST_NAME, TEST_MEASURE, TEST_MEASURE_NAME, TEST_TYPE, TEST_TYPE_NAME, UOM, UOM_NAME

	  
Operational Fields: ID, TEST_NAME, TEST_MEASURE, TEST_MEASURE_NAME, TEST_TYPE, TEST_TYPE_NAME, UOM, UOM_NAME

         
PARAMETER  :       pPROD_TYPE (COME FROM 2ND API ->PROD_TYPE_NAME ) 

Table Name:   	   FUNCTION JERP_PP_UTIL.FD_QC_IPQC_TEST_LIST(pPROD_TYPE VARCHAR) 

 
Relation : 	
            

Filter by:   

GROUP BY: 

QUERY : 

SELECT JERP_PP_UTIL.FD_QC_IPQC_TEST_LIST(:pPROD_TYPE) FROM DUAL; ----RAW-PACK, WIP




----------------------------------------------------------------
--RIGHT PANEL  BODY -   - 6th API--NEEDS MODIFICATION
API TYPE : GET
API NAME : api/pp/get-test-spec-data/{pQC_PARAM_ID}/{pQC_PARAM_PROCESS_ID}

Response Fields :  
	  PS.TEST_SERIAL_NO, PS.TEST_ID, AC.ELEMENT_NAME = TEST_NAME, AC.ELEMENT_NAME = TEST_TYPE_NAME, PS.SPECIFICATION
	  
Operational Fields: 
	PS.ID, PS.QC_PARAM_ID, PS.VERSION_NO, PS.TEST_TYPE, AC.ELEMENT_NAME = TEST_TYPE_NAME, PS.TEST_ID, AC.ELEMENT_NAME = TEST_NAME, 
	PS.SPECIFICATION, PS.TEST_SERIAL_NO, PS.SORT_ORDER, PS.STATUS, 
    PS.CREATED_BY, PS.CREATED_AT, PS.UPDATED_BY, PS.UPDATED_AT, PS.QC_PARAM_PROCESS_ID
    
PARAMETER : PS.QC_PARAM_ID = :pQC_PARAM_ID AND PS.QC_PARAM_PROCESS_ID = :pQC_PARAM_PROCESS_ID

Table Name: 
            PP_QC_PARAM_SPEC = PS
            ADM_CODE_ELEMENTS = AC         
            ADM_CODE_ELEMENTS = ACC  
             
            
Relation :  
            PS.TEST_TYPE=AC.ID
             PS.TEST_ID=ACC.ID
              
  
Filter by:   
            
                  
QUERY :  

SELECT PS.ID, PS.QC_PARAM_ID, PS.VERSION_NO, PS.TEST_TYPE, AC.ELEMENT_NAME AS TEST_TYPE_NAME, PS.TEST_ID, PQIT.TEST_NAME, PS.SPECIFICATION, PS.TEST_SERIAL_NO, PS.SORT_ORDER, PS.STATUS, 
PS.CREATED_BY, PS.CREATED_AT, PS.UPDATED_BY, PS.UPDATED_AT, PS.QC_PARAM_PROCESS_ID
FROM PP_QC_PARAM_SPEC PS
JOIN ADM_CODE_ELEMENTS AC ON PS.TEST_TYPE=AC.ID
JOIN PP_QC_IPQC_TEST PQIT ON PS.TEST_ID=PQIT.ID
WHERE PS.QC_PARAM_ID = :pQC_PARAM_ID --10047
AND PS.QC_PARAM_PROCESS_ID = :pQC_PARAM_PROCESS_ID  --10058
ORDER BY TEST_SERIAL_NO

--OLD QRY
/*  
SELECT PS.ID, PS.QC_PARAM_ID, PS.VERSION_NO, PS.TEST_TYPE, AC.ELEMENT_NAME AS TEST_TYPE_NAME, PS.TEST_ID, ACC.ELEMENT_NAME AS TEST_NAME, PS.SPECIFICATION, PS.TEST_SERIAL_NO, PS.SORT_ORDER, PS.STATUS, 
PS.CREATED_BY, PS.CREATED_AT, PS.UPDATED_BY, PS.UPDATED_AT, PS.QC_PARAM_PROCESS_ID
FROM PP_QC_PARAM_SPEC PS
JOIN ADM_CODE_ELEMENTS AC ON PS.TEST_TYPE=AC.ID
JOIN ADM_CODE_ELEMENTS ACC ON PS.TEST_ID=ACC.ID
WHERE PS.QC_PARAM_ID = :pQC_PARAM_ID --10047
AND PS.QC_PARAM_PROCESS_ID is null--= :pQC_PARAM_PROCESS_ID  --10058
ORDER BY TEST_SERIAL_NO
*/

-----------------------------------------------------------------------
--api/pp/qc-param-spec-details/6002 --PROD_ID (qc_param and qc_param_spec_info)
--RIGHT PANEL  BODY -   -  API--NEEDS MODIFICATION
API TYPE : GET
API NAME : api/pp/get-test-raw-spec-data/{pQC_PARAM_ID}

Response Fields :  
	  PS.TEST_SERIAL_NO, PS.TEST_ID, AC.ELEMENT_NAME = TEST_NAME, AC.ELEMENT_NAME = TEST_TYPE_NAME, PS.SPECIFICATION
	  
Operational Fields: 
	PS.ID, PS.QC_PARAM_ID, PS.VERSION_NO, PS.TEST_TYPE, AC.ELEMENT_NAME = TEST_TYPE_NAME, PS.TEST_ID, AC.ELEMENT_NAME = TEST_NAME, 
	PS.SPECIFICATION, PS.TEST_SERIAL_NO, PS.SORT_ORDER, PS.STATUS, 
    PS.CREATED_BY, PS.CREATED_AT, PS.UPDATED_BY, PS.UPDATED_AT, PS.QC_PARAM_PROCESS_ID
    
PARAMETER : PS.QC_PARAM_ID = :pQC_PARAM_ID AND PS.QC_PARAM_PROCESS_ID = :pQC_PARAM_PROCESS_ID

Table Name: 
            PP_QC_PARAM_SPEC = PS
            ADM_CODE_ELEMENTS = AC         
            ADM_CODE_ELEMENTS = ACC  
             
            
Relation :  
            PS.TEST_TYPE=AC.ID
             PS.TEST_ID=ACC.ID
              
  
Filter by:   
            
                  
QUERY :  

SELECT PS.ID, PS.QC_PARAM_ID, PS.VERSION_NO, PS.TEST_TYPE, AC.ELEMENT_NAME AS TEST_TYPE_NAME, PS.TEST_ID, PQIT.TEST_NAME, PS.SPECIFICATION, PS.TEST_SERIAL_NO, PS.SORT_ORDER, PS.STATUS, 
PS.CREATED_BY, PS.CREATED_AT, PS.UPDATED_BY, PS.UPDATED_AT, PS.QC_PARAM_PROCESS_ID
FROM PP_QC_PARAM_SPEC PS
JOIN ADM_CODE_ELEMENTS AC ON PS.TEST_TYPE=AC.ID
JOIN PP_QC_IPQC_TEST PQIT ON PS.TEST_ID=PQIT.ID
WHERE PS.QC_PARAM_ID = :pQC_PARAM_ID --10039
AND PS.QC_PARAM_PROCESS_ID IS NULL
ORDER BY TEST_SERIAL_NO