
SELECT TRANSACTION_ID FROM PP_QC_SAMPLE_ASSIGN WHERE LAB_CONTROL_CODE ='LAB-00023/22';

SELECT TRANSACTION_ID 
  FROM PP_QC_SAMPLE_ASSIGN 
 WHERE LAB_CONTROL_CODE in (SELECT LAB_CONTROL_CODE 
                              FROM PP_QC_TEST_MST 
                             WHERE ID = 10072
                           );
                           
SELECT PQSA.TRANSACTION_ID,LOT_QTY,PASSED_QTY,USED_QC_QTY,TEST_STATUS,ACE.ELEMENT_NAME,PQSA.PROD_ID 
FROM PP_QC_TEST_MST PQTM
LEFT JOIN PP_QC_SAMPLE_ASSIGN PQSA ON PQSA.LAB_CONTROL_CODE = PQTM.LAB_CONTROL_CODE
LEFT JOIN ADM_CODE_ELEMENTS ACE ON ACE.ID = PQTM.TEST_STATUS
WHERE PQTM.ID = 10072
AND PQTM.STATUS=1

SELECT * FROM ADM_CODE_ELEMENTS
WHERE ID=7032
                      


