
SELECT * FROM ADM_PRODUCT_LOT
WHERE EXP_DATE>TRUNC(SYSDATE)
AND RETEST_DATE BETWEEN TRUNC(SYSDATE) AND TRUNC(SYSDATE+30);

SELECT * FROM SD_WH_STORE_STOCK
WHERE PROD_ID IN (
SELECT PROD_ID FROM ADM_PRODUCT_LOT
WHERE EXP_DATE>TRUNC(SYSDATE)
AND RETEST_DATE BETWEEN TRUNC(SYSDATE) AND TRUNC(SYSDATE+30)
)
AND CURRENT_STOCK>NVL(BLOCKED_STOCK,0)+NVL(ORDERED_QTY,0);


SELECT APL.ID,APL.LOT_NO,APL.PROD_ID,AP.PROD_NAME, TRUNC(APL.MFG_DATE) MFG_DATE
FROM ADM_PRODUCT_LOT APL
LEFT JOIN SD_WH_STORE_STOCK SWSS ON SWSS.PROD_ID = APL.PROD_ID
LEFT JOIN ADM_PRODUCTS AP ON AP.ID = APL.PROD_ID
WHERE APL.EXP_DATE>TRUNC(SYSDATE)
AND APL.SBU_ID = :pSBU_ID
AND APL.RETEST_DATE BETWEEN TRUNC(SYSDATE) AND TRUNC(SYSDATE+30)
AND SWSS.CURRENT_STOCK>NVL(SWSS.BLOCKED_STOCK,0)+NVL(SWSS.ORDERED_QTY,0);


SELECT ID,CONTAINER_NO,CON_VOLUMN 
FROM ADM_GRN_CONTAINER
WHERE GRN_ID = :pGRN_ID