
--RESTRICTED- DEFAULT IN
SELECT * FROM ADM_WAREHOUSE_STORE WHERE STORE_TYPE=442 AND WAREHOUSE_ID IN(SELECT ID FROM ADM_WAREHOUSE WHERE WH_CODE='FAC')

--UN-RESTRICTED- DEFAULT OUT
SELECT * FROM ADM_WAREHOUSE_STORE WHERE STORE_TYPE=443 AND WAREHOUSE_ID IN(SELECT ID FROM ADM_WAREHOUSE WHERE WH_CODE='FAC')

------------

---ADM_GRN
SELECT WAREHOUSE_ID FROM ADM_GRN --205(RAW)/ 206(PACK)

--DEFAULT STOCK IN (RESTRICTED)-WITH 0 STOCK
SELECT STORE_ID FROM SD_WH_STORE_STOCK --114(RAW)/ 119(PACK)

--STOCK RECEIVE-IN-(RESTRICTED)-WITH STOCK QTY
SELECT STORE_ID FROM SD_WH_STORE_STOCK --114(RAW)/ 119(PACK)

--AFTER QC PASS- DEFAULT STOCK IN(UN-RESTRICTED)
SELECT STORE_ID FROM SD_WH_STORE_STOCK --115(RAW)/ 120(PACK)

--AFTER QC PASS- DEFAULT STOCK OUT(RESTRICTED)
SELECT STORE_ID FROM SD_WH_STORE_STOCK --114(RAW)/ 119(PACK)

--DISPENSE REQUISITION --AVAILABLE STOCK SHOW
SELECT REQ_TO_WH FROM MM_INT_REQ_MST  ----205(RAW)/ 206(PACK)
--JERP_INVENTORY_UTIL.AVAILABLE_QUANTITY(JERP_INVENTORY_UTIL.GET_STORE (MIRM.REQ_TO_WH, 'OUT'), MIRD.PROD_ID) AVAILABLE_BATCH_QTY
--JERP_INVENTORY_UTIL.GET_STORE (MIRM.REQ_TO_WH, 'OUT')-MULTIPLE STORES ID NEEDED TO GET ACTUAL STOCK

--MATERIAL ISSUE-
SELECT ISS_FROM_WH, ISS_TO_WH FROM MM_INT_ISS_MST ------FROM --205(RAW)/ 206(PACK)--TO--