

select * from adm_grn

SELECT * FROM ADM_SBU_PRODUCTS
WHERE PROD_ID=7282


SELECT * FROM ADM_CODE_ELEMENTS
WHERE CODE_ID=722

SELECT * FROM ADM_GRN
WHERE ID=3419

SELECT * FROM ADM_GRN_DETAIL
WHERE GRN_ID = :pGRN_ID
AND PROD_ID = :pPROD_ID

SELECT AGD.PROD_ID CODE_NO,ASP.DISPLAY_NAME PROD_NAME,AGD.BATCH_LOT_NO,AG.CHALLAN_NO,AG.GRN_NO,SUP.SUPPLIER_NAME,AGD.CONTAINER_COUNT,
AGC.CONTAINER_NO,AGD.MFG_DATE,AGD.EXP_DATE,AGC.CON_VOLUMN,ACE.ELEMENT_NAME UOM_NAME,
(SELECT SUM(NVL(CON_VOLUMN,0)) FROM ADM_GRN_CONTAINER WHERE GRN_ID = :pGRN_ID) TOT_QTY
FROM ADM_GRN AG
LEFT JOIN ADM_GRN_DETAIL AGD ON AG.ID = AGD.GRN_ID
LEFT JOIN ADM_SBU_PRODUCTS ASP ON ASP.PROD_ID = AGD.PROD_ID AND ASP.SBU_ID = AG.SBU_ID
LEFT JOIN MM_PUR_ORD_MST MPOM ON MPOM.ID = AG.PO_ID 
LEFT JOIN ADM_SUPPLIERS SUP ON SUP.ID = MPOM.SUPPLIER_ID
LEFT JOIN ADM_GRN_CONTAINER AGC ON AG.ID = AGC.GRN_ID AND AGD.GRN_ID=AGC.GRN_ID
LEFT JOIN ADM_CODE_ELEMENTS ACE ON ACE.ID = AGC.CON_VOLUMN_UOM
WHERE AG.ID = :pGRN_ID
AND AGD.PROD_ID = :pPROD_ID
AND ASP.SBU_ID=2
AND AGC.CONTAINER_NO =:pCONTAINER_NO


---
SELECT PQSA.LAB_CONTROL_CODE QC_REF_NO,PQS.CONTAINER_NO,PQS.SAMPLE_QTY,ACE.ELEMENT_NAME SAMPLE_UOM,PQTM.POTENCY,PQTM.RE_TEST_DATE 
FROM PP_QC_SAMPLE_ASSIGN PQSA
LEFT JOIN PP_QC_SAMPLING PQS ON PQS.QC_SAMPLE_ID = PQSA.ID
LEFT JOIN PP_QC_TEST_MST PQTM ON PQSA.LAB_CONTROL_CODE = PQTM.LAB_CONTROL_CODE
LEFT JOIN ADM_CODE_ELEMENTS ACE ON ACE.ID = PQS.SAMPLE_UOM
WHERE TRANSACTION_ID=3419
AND PROD_ID = :pPROD_ID
AND PQS.CONTAINER_NO=:pCONTAINER_NO



SELECT * FROM PP_PRODUCT_BATCH

SELECT * FROM PP_PROD_BATCH_MAP

--------

WITH Q1 AS (
SELECT AGD.PROD_ID CODE_NO,ASP.DISPLAY_NAME PROD_NAME,AGD.BATCH_LOT_NO,AG.CHALLAN_NO,AG.GRN_NO,SUP.SUPPLIER_NAME,AGD.CONTAINER_COUNT,
       AGC.CONTAINER_NO,AGD.MFG_DATE,AGD.EXP_DATE,AGC.CON_VOLUMN,ACE.ELEMENT_NAME UOM_NAME,
       (SELECT SUM(NVL(CON_VOLUMN,0)) FROM ADM_GRN_CONTAINER WHERE GRN_ID = :pGRN_ID) TOT_QTY,:pSTICKER_TYPE STICKER_TYPE
  FROM ADM_GRN AG
  LEFT JOIN ADM_GRN_DETAIL AGD ON AG.ID = AGD.GRN_ID
  LEFT JOIN ADM_SBU_PRODUCTS ASP ON ASP.PROD_ID = AGD.PROD_ID AND ASP.SBU_ID = AG.SBU_ID
  LEFT JOIN MM_PUR_ORD_MST MPOM ON MPOM.ID = AG.PO_ID 
  LEFT JOIN ADM_SUPPLIERS SUP ON SUP.ID = MPOM.SUPPLIER_ID
  LEFT JOIN ADM_GRN_CONTAINER AGC ON AG.ID = AGC.GRN_ID AND AGD.GRN_ID=AGC.GRN_ID
  LEFT JOIN ADM_CODE_ELEMENTS ACE ON ACE.ID = AGC.CON_VOLUMN_UOM
 WHERE AG.ID = :pGRN_ID
   AND AGD.PROD_ID = :pPROD_ID
   AND ASP.SBU_ID = :pSBU_ID
   AND AGC.CONTAINER_NO =:pCONTAINER_NO
), Q2 AS (
SELECT PQSA.LAB_CONTROL_CODE QC_REF_NO,PQS.CONTAINER_NO,PQS.SAMPLE_QTY,ACE.ELEMENT_NAME SAMPLE_UOM,PQTM.POTENCY,PQTM.RE_TEST_DATE 
  FROM PP_QC_SAMPLE_ASSIGN PQSA
  LEFT JOIN PP_QC_SAMPLING PQS ON PQS.QC_SAMPLE_ID = PQSA.ID
  LEFT JOIN PP_QC_TEST_MST PQTM ON PQSA.LAB_CONTROL_CODE = PQTM.LAB_CONTROL_CODE
  LEFT JOIN ADM_CODE_ELEMENTS ACE ON ACE.ID = PQS.SAMPLE_UOM
 WHERE TRANSACTION_ID = :pGRN_ID
   AND PROD_ID = :pPROD_ID
   AND PQS.CONTAINER_NO = :pCONTAINER_NO
)
SELECT JSON_OBJECT (
                        'material_name'     VALUE A.PROD_NAME,
                        'batch_lot_no'      VALUE A.BATCH_LOT_NO,
                        'challan_no'        VALUE A.CHALLAN_NO,
                        'code_no'           VALUE A.CODE_NO,
                        'grn_no'            VALUE A.GRN_NO,
                        'supplier'          VALUE A.SUPPLIER_NAME,
                        'container'         VALUE A.CONTAINER_COUNT,
                        'quantity'          VALUE A.TOT_QTY,
                        'uom'               VALUE A.UOM_NAME,
                        'mfg_date'          VALUE TO_CHAR(A.MFG_DATE,'DD-MM-RRRR'),
                        'exp_date'          VALUE TO_CHAR(A.EXP_DATE,'DD-MM-RRRR'),
                        'remarks'           VALUE ''
                   )  FROM (SELECT * FROM Q1) A



/*
  SELECT JSON_OBJECT (
                        'sticker_type'     VALUE A.STICKER_TYPE,
                        'aa' value (
                                    if A.STICKER_TYPE = 7451 then
                                        select json_object (
                                                            'a' value 'b'
                                                           ) FROM (SELECT * FROM Q1) A 
                                    end if;
                                   )
                       )FROM (SELECT * FROM Q1) A --1ST OBJ

--IF :pSTICKER_TYPE = 7451 THEN
--END IF;


SELECT JSON_OBJECT (
                    'sticker_type' VALUE STICKER_TYPE) QRY_OUTPUT
           FROM (
           SELECT AGD.PROD_ID CODE_NO,ASP.DISPLAY_NAME PROD_NAME,AGD.BATCH_LOT_NO,AG.CHALLAN_NO,AG.GRN_NO,SUP.SUPPLIER_NAME,AGD.CONTAINER_COUNT,
       AGC.CONTAINER_NO,AGD.MFG_DATE,AGD.EXP_DATE,AGC.CON_VOLUMN,ACE.ELEMENT_NAME UOM_NAME,
       (SELECT SUM(NVL(CON_VOLUMN,0)) FROM ADM_GRN_CONTAINER WHERE GRN_ID = :pGRN_ID) TOT_QTY,:pSTICKER_TYPE STICKER_TYPE
  FROM ADM_GRN AG
  LEFT JOIN ADM_GRN_DETAIL AGD ON AG.ID = AGD.GRN_ID
  LEFT JOIN ADM_SBU_PRODUCTS ASP ON ASP.PROD_ID = AGD.PROD_ID AND ASP.SBU_ID = AG.SBU_ID
  LEFT JOIN MM_PUR_ORD_MST MPOM ON MPOM.ID = AG.PO_ID 
  LEFT JOIN ADM_SUPPLIERS SUP ON SUP.ID = MPOM.SUPPLIER_ID
  LEFT JOIN ADM_GRN_CONTAINER AGC ON AG.ID = AGC.GRN_ID AND AGD.GRN_ID=AGC.GRN_ID
  LEFT JOIN ADM_CODE_ELEMENTS ACE ON ACE.ID = AGC.CON_VOLUMN_UOM
 WHERE AG.ID = :pGRN_ID
   AND AGD.PROD_ID = :pPROD_ID
   AND ASP.SBU_ID = :pSBU_ID
   AND AGC.CONTAINER_NO =:pCONTAINER_NO) a