SELECT * FROM PP_WIP_MST;

SELECT * FROM PP_WIP_PROCESS;

SELECT * FROM PP_WIP_PROC_TIME;
SELECT * FROM PP_WIP_PROC_EMP;
SELECT * FROM PP_WIP_PROC_MACH;
SELECT * FROM PP_WIP_PROC_INPUT;
SELECT * FROM PP_WIP_PROC_OUTPUT;
SELECT * FROM PP_WIP_QCOM_SAMPLE;


--WIP PRODUCT LIST-LEFT PANEL-LANDING MODE---

SELECT   JERP_PP_UTIL.FD_GET_WIP_PRODUCT_LIST(2) FROM DUAL;

SELECT PB.ID BATCH_ID, PB.BATCH_NO, PB.PROD_ID, AP.PROD_NAME, PB.BATCH_SIZE, PB.SIZE_UOM, FD_GET_BASE_UOM(PB.SIZE_UOM) AS SIZE_UOM_NAME, PB.BATCH_START_DATE,
PB.PROD_LOCATION_ID, AW.WH_NAME PROD_LOCATION_NAME, PLB.PROD_LINE_ID, PL.PLANT_ID, AP.PLANT_NAME, PL.PRODUCTION_LINE_ID, APP.PLANT_NAME PRODUCTION_LINE_NAME
FROM PP_PRODUCT_BATCH PB
JOIN ADM_PRODUCTS AP ON AP.ID = PB.PROD_ID
LEFT JOIN ADM_WAREHOUSE AW ON PB.PROD_LOCATION_ID=AW.ID
LEFT JOIN PP_PROD_LINE_BATCH PLB ON PB.ID=PLB.BATCH_ID 
LEFT JOIN PP_PROD_LINE_ALLO PL ON PLB.PROD_LINE_ID=PL.ID
LEFT JOIN ADM_PLANT AP ON PL.PLANT_ID=AP.ID
LEFT JOIN ADM_PLANT APP ON PL.PRODUCTION_LINE_ID=APP.ID
WHERE PB.IS_TRANSFERED = 'N' AND PB.TRANSFER_ID IS NULL AND NVL(PB.TRANSFER_QTY,0) = 0 AND AP.PROD_TYPE=506
--AND PPB.SBU_ID = :pSBU_ID
ORDER BY PB.CREATED_AT DESC;


--SELECT PROCESS_SUB_PROCESS_LIST(107, 10230) PROCESS_DT FROM DUAL; ---PROD_ID (ID OF ADM_PRODUCTS) AND BATCH_ID (ID OF PP_PRODUCT_BATCH)

SELECT JERP_PP_UTIL.FD_GET_WIP_PROCESS_SUB_PROCESS_LIST(107, 10230) PROCESS_DT FROM DUAL;

-------BATCH-PRODUCT WISE PROCESS-SUB-PROCESS LIST- SEQUENCE WISE---

SELECT PB.ID BATCH_ID, PB.BATCH_NO, PB.PROD_ID, AP.PROD_NAME, TP.PROCESS_ID, PC.PROCESS_NAME, TP.SUB_PROCESS_ID, PC1.PROCESS_NAME SUB_PROCESS_NAME, TP.PROCESS_SEQUENCE, WP.PROCESS_STATUS, WP.IS_COMPLETED, WP.IS_SKIPPED
FROM PP_PRODUCT_BATCH PB
JOIN ADM_PRODUCTS AP ON AP.ID = PB.PROD_ID
JOIN PP_PROD_PROC_TYPE PT ON PB.PROD_ID=PT.PROD_ID 
JOIN PP_PROC_TYPE_PROCESS TP ON PT.ID=TP.PROD_PROC_TYPE_ID
LEFT JOIN PP_PROCESS_CONFIG PC ON TP.PROCESS_ID=PC.ID
LEFT JOIN PP_PROCESS_CONFIG PC1 ON TP.SUB_PROCESS_ID=PC1.ID
LEFT JOIN PP_WIP_MST WM ON PB.ID=WM.BATCH_ID AND PB.PROD_ID=WM.PROD_ID
LEFT JOIN PP_WIP_PROCESS WP ON (WM.ID=WP.WIP_MST_ID AND TP.PROCESS_ID=WP.PROCESS_ID) OR (WM.ID=WP.WIP_MST_ID AND TP.PROCESS_ID=WP.PROCESS_ID AND TP.SUB_PROCESS_ID=WP.SUB_PROCESS_ID)
WHERE PB.PROD_ID=107 AND PB.ID=10230
ORDER BY TP.PROCESS_SEQUENCE;