-----GOODS RECEIVE NOTES MASTER-DETAILS INFO-----
SELECT AG.ID GRN_ID, AG.OFFICE_ID, AP.PLANT_NAME OFFICE_NAME, AG.GRN_NO, AG.GRN_DATE, AG.GRN_SOURCE, AG.REF_NO, AG.WAREHOUSE_ID, AW.WH_NAME, AG.QC_REQUIRED, 
AG.QC_PASS_STATUS, AG.RECEIVED_BY, AG.RECEIVED_DATE, AG.IS_COMPLETED, AG.IS_RETURNED, AG.RETURN_GRN_ID, 
AG.PI_NO, AG.PI_DATE, AG.CI_NO, AG.CI_DATE, AG.CHALLAN_NO, AG.CHALLAN_DATE, AG.PO_ID, AG.STORAGE_CONDITION, AG.INDICATION, AG.QC_PRIORITY, AG.REMARKS,
AGD.ID GRN_DTL_ID, AGD.PROD_ID, APR.PROD_NAME, AGD.PROD_UOM, FD_GET_BASE_UOM(AGD.PROD_UOM) AS PROD_UOM_NAME, AGD.BATCH_LOT_NO, AGD.NEW_BATCH_NO, 
AGD.POTENCY, AGD.MFG_DATE, AGD.EXP_DATE, AGD.GRN_QTY, AGD.RCV_QTY, 
AGD.QC_PASSED_QTY, AGD.QC_NOTE, AGD.QC_BY, AGD.QC_DATE, AGD.QTY_MISMATCH_NOTE, AGD.DAMMAGED_NOTE
FROM ADM_GRN AG JOIN ADM_GRN_DETAIL AGD ON AG.ID=AGD.GRN_ID
LEFT JOIN ADM_PLANT AP ON AG.OFFICE_ID=AP.ID
LEFT JOIN ADM_WAREHOUSE AW ON AG.WAREHOUSE_ID=AW.ID
LEFT JOIN ADM_PRODUCTS APR ON AGD.PROD_ID=APR.ID
WHERE AG.GRN_SOURCE IN('IMPORT-PURCHASE','LOCAL-PURCHASE');
--WHERE AG.OFFICE_ID=4;


---GOODS RECEIVE NOTE-GRN CONTAINER DETAILS----
SELECT AG.ID GRN_ID, AG.GRN_NO, AG.GRN_DATE, AG.GRN_SOURCE, AGD.ID GRN_DTL_ID, AGD.PROD_ID, APR.PROD_NAME,
AGC.ID GRN_CONT_ID, AGC.IMCS_NO, AGC.SL_NO, AGC.CONTAINER_NO, AGC.CONTAINER_TYPE, ACE.ELEMENT_NAME CONT_TYPE_NAME, 
AGC.CON_VOLUMN, AGC.CON_VOLUMN_UOM, FD_GET_BASE_UOM(AGC.CON_VOLUMN_UOM) AS VOLUMN_UOM_NAME, AGC.INTACT_FLAG, AGC.REMARKS
FROM ADM_GRN AG JOIN ADM_GRN_DETAIL AGD ON AG.ID=AGD.GRN_ID
JOIN ADM_GRN_CONTAINER AGC ON AG.ID=AGC.GRN_ID AND AGD.ID=AGC.GRNDTL_ID
LEFT JOIN ADM_PRODUCTS APR ON AGD.PROD_ID=APR.ID
LEFT JOIN ADM_CODE_ELEMENTS ACE ON AGC.CONTAINER_TYPE=ACE.ID
WHERE AG.GRN_SOURCE IN('IMPORT-PURCHASE','LOCAL-PURCHASE');

SELECT IMCS_NO, SL_NO, CONTAINER_NO,ACE.ELEMENT_NAME CONTAINER_TYPE_NAME,
       CON_VOLUMN,UOM.ELEMENT_NAME, INTACT_FLAG, REMARKS 
  FROM ADM_GRN_DETAIL AGD
  JOIN ADM_GRN_CONTAINER AGC ON AGD.GRN_ID = AGC.GRN_ID AND AGD.ID=AGC.GRNDTL_ID
  LEFT JOIN ADM_CODE_ELEMENTS ACE ON AGC.CONTAINER_TYPE=ACE.ID
  LEFT JOIN ADM_CODE_ELEMENTS UOM ON AGC.CON_VOLUMN_UOM=UOM.ID
 WHERE AGC.GRN_ID=3409