
SELECT * FROM PP_BATCH_DOC_MST;

SELECT * FROM PP_BATCH_DOC_DTL;

SELECT * FROM PP_BATCH_DOC_PROD;

SELECT * FROM PP_PROD_BATCH_MAP;

SELECT PBDM.ID REQ_ID,PBDP.TRANSFER_PROD_ID AS PROD_ID,AP.PROD_NAME, PBDM.DISPLAY_CODE REQ_NO,NVL(AP.COM_PACK_SIZE,AP.EXP_PACK_SIZE) PAK_SIZE,
PBDP.REQUIRED_QTY,JERP_ADM.FD_GET_BASE_UOM(PBDP.REQUIRED_UOM ) UOM,PPBM.DOC_ID
FROM PP_BATCH_DOC_PROD PBDP
LEFT JOIN PP_BATCH_DOC_DTL PBDD ON PBDD.ID = PBDP.BATCH_DOC_DETAIL_ID
LEFT JOIN PP_BATCH_DOC_MST PBDM ON PBDM.ID = PBDD.DOC_REQ_ID
LEFT JOIN ADM_PRODUCTS AP ON AP.ID = PBDP.TRANSFER_PROD_ID
LEFT JOIN PP_PROD_BATCH_MAP PPBM ON PPBM.PROD_ID = PBDP.TRANSFER_PROD_ID



