--------qc and ipqc test data --------------

SELECT PQTD.TEST_SL_NO,PQTD.TEST_ID,PQTD.TEST_NAME,PQTD.SPECIFICATION,PQTD.TEST_RESULT_VALUE,
       PQTD.PARENT_TEST_ID,PQTM.TEST_STATUS,ACE.ELEMENT_NAME
  FROM PP_QC_TEST_DTL PQTD
  JOIN PP_QC_TEST_MST PQTM ON PQTD.TEST_RESULT_ID = PQTM.ID
  JOIN PP_QC_SAMPLE_ASSIGN PQSA ON PQTM.LAB_CONTROL_CODE = PQSA.LAB_CONTROL_CODE
  JOIN PP_WIP_QCOM_SAMPLE PWQS ON PQSA.ID = PWQS.LAB_CONTROL_ID AND PQSA.TRANSACTION_ID = PWQS.ID
  LEFT JOIN ADM_CODE_ELEMENTS ACE ON PQTM.TEST_STATUS = ACE.ID
 WHERE PWQS.WIP_PROCESS_ID = :pWIP_PROCESS_ID    

-----get data machine and sampling----------
SELECT PWPT.ID, PWPT.WIP_PROCESS_ID, PWPT.TIMING_ACTION,ACE.ELEMENT_NAME TIMING_ACTION_NAME, TO_CHAR(PWPT.PROCESS_DATE,'DD-MON-RRRR') PROCESS_DATE, 
TO_CHAR(PWPT.START_TIME,'HH12:MI:SS AM') START_TIME, TO_CHAR(PWPT.END_TIME,'HH12:MI:SS AM') END_TIME, PWPT.TOTAL_TIME_CONS, PWPT.REMARKS,PWPT.CREATED_BY,AU.NAME
FROM PP_WIP_PROC_TIME PWPT
LEFT JOIN ADM_CODE_ELEMENTS ACE ON ACE.ID = PWPT.TIMING_ACTION
LEFT JOIN ADM_USERS AU ON AU.ID = PWPT.CREATED_BY
WHERE WIP_PROCESS_ID=10151



SELECT PWQS.ID, WIP_PROCESS_ID, SL_NO, PWQS.PROD_ID,ASP.DISPLAY_NAME, ITEM_NAME, SAMPLE_QTY, SAMPLE_UOM,ACE.ELEMENT_NAME SAMPLE_UOM_NAME, 
SAMPLING_PURPOSE, ACE1.ELEMENT_NAME SAMPLING_PURPOSE_NAME,TESTING_DEPARTMENT,ACE2.ELEMENT_NAME TESTING_DEPARTMENT_NAME,
 SAMPLING_STAGE,ACE3.ELEMENT_NAME SAMPLING_STAGE_NAME, INSTRUCTIONS, SAMPLING_TIME, SAMPLE_BY, QC_TEST_MST_ID,QC_STATUS, LAB_CONTROL_ID
 FROM PP_WIP_QCOM_SAMPLE PWQS
 LEFT JOIN ADM_SBU_PRODUCTS ASP ON PWQS.PROD_ID = ASP.PROD_ID
 LEFT JOIN ADM_CODE_ELEMENTS ACE ON ACE.ID = PWQS.SAMPLE_UOM
 LEFT JOIN ADM_CODE_ELEMENTS ACE1 ON ACE1.ID = PWQS.SAMPLING_PURPOSE
 LEFT JOIN ADM_CODE_ELEMENTS ACE2 ON ACE2.ID = PWQS.TESTING_DEPARTMENT
   LEFT JOIN ADM_CODE_ELEMENTS ACE3 ON ACE3.ID = PWQS.SAMPLING_STAGE
WHERE WIP_PROCESS_ID=10120