
DELETE PP_WIP_PROC_TIME WHERE WIP_PROCESS_ID IN(SELECT ID FROM PP_WIP_PROCESS 
WHERE WIP_MST_ID IN(SELECT ID FROM PP_WIP_MST WHERE PROD_ID=183 AND BATCH_ID=11678));

COMMIT;

DELETE PP_WIP_PROC_INPUT WHERE WIP_PROCESS_ID IN(SELECT ID FROM PP_WIP_PROCESS 
WHERE WIP_MST_ID IN(SELECT ID FROM PP_WIP_MST WHERE PROD_ID=183 AND BATCH_ID=11678));

COMMIT;

DELETE PP_WIP_PROC_OUTPUT WHERE WIP_PROCESS_ID IN(SELECT ID FROM PP_WIP_PROCESS 
WHERE WIP_MST_ID IN(SELECT ID FROM PP_WIP_MST WHERE PROD_ID=183 AND BATCH_ID=11678));

COMMIT;

DELETE PP_WIP_PROC_EMP WHERE WIP_PROCESS_ID IN(SELECT ID FROM PP_WIP_PROCESS 
WHERE WIP_MST_ID IN(SELECT ID FROM PP_WIP_MST WHERE PROD_ID=183 AND BATCH_ID=11678));

COMMIT;

DELETE PP_WIP_PROC_MACH WHERE WIP_PROCESS_ID IN(SELECT ID FROM PP_WIP_PROCESS 
WHERE WIP_MST_ID IN(SELECT ID FROM PP_WIP_MST WHERE PROD_ID=183 AND BATCH_ID=11678));

COMMIT;

DELETE PP_WIP_PROCESS WHERE WIP_MST_ID IN(SELECT ID FROM PP_WIP_MST WHERE PROD_ID=183 AND BATCH_ID=11678);

COMMIT;

DELETE PP_WIP_MST WHERE PROD_ID=183 AND BATCH_ID=11678;

COMMIT;

