
--1-- PROCESS-- SUB-PROCESS ---

SELECT PWP.ID,PROCESS_ID,PPC.PROCESS_NAME PROCESS,SUB_PROCESS_ID,PPC1.PROCESS_NAME SUB_PROCESS, PROCESS_START_DATE, PROCESS_END_DATE,
       PROCESS_STATUS STATUS,ACE.ELEMENT_NAME, TOTAL_PROCESS_HOUR,IS_COMPLETED, IS_SKIPPED, PROCESS_SEQUENCE SEQ,PWP.WIP_STAGE_ID STAGE
FROM PP_WIP_PROCESS PWP
LEFT JOIN PP_PROCESS_CONFIG PPC ON PWP.PROCESS_ID = PPC.ID 
LEFT JOIN PP_PROCESS_CONFIG PPC1 ON  PWP.SUB_PROCESS_ID = PPC1.ID 
LEFT JOIN ADM_CODE_ELEMENTS ACE ON PWP.PROCESS_STATUS = ACE.ID
WHERE WIP_MST_ID IN (
SELECT ID FROM PP_WIP_MST WHERE PROD_ID = :pPROD_ID AND BATCH_ID = :pBATCH_ID)
ORDER BY PROCESS_SEQUENCE;


--2-- PROCESS TIME----

SELECT PWPT.ID, WIP_PROCESS_ID,PWP.PROCESS_SEQUENCE SEQ,PWP.PROCESS_ID,PPC.PROCESS_NAME,PWP.SUB_PROCESS_ID,PPC1.PROCESS_NAME SUB_PROCESS_NAME,
       TIMING_ACTION,ACE.ELEMENT_NAME, PROCESS_DATE, START_TIME, END_TIME, TOTAL_TIME_CONS TOTAL_TIME 
FROM PP_WIP_PROC_TIME PWPT
LEFT JOIN PP_WIP_PROCESS PWP ON PWPT.WIP_PROCESS_ID = PWP.ID
LEFT JOIN PP_PROCESS_CONFIG PPC ON PWP.PROCESS_ID = PPC.ID 
LEFT JOIN PP_PROCESS_CONFIG PPC1 ON  PWP.SUB_PROCESS_ID = PPC1.ID 
LEFT JOIN ADM_CODE_ELEMENTS ACE ON PWPT.TIMING_ACTION = ACE.ID
WHERE PWP.WIP_MST_ID IN (
SELECT ID FROM PP_WIP_MST WHERE PROD_ID = :pPROD_ID AND BATCH_ID = :pBATCH_ID)
ORDER BY PWPT.ID DESC,PWP.PROCESS_SEQUENCE DESC;


--5-- PROCESS OUTPUT ---

SELECT PWPO.ID, WIP_PROCESS_ID,PWP.PROCESS_SEQUENCE PROC_SEQ,PWP.PROCESS_ID,PPC.PROCESS_NAME,PWP.SUB_PROCESS_ID,PPC1.PROCESS_NAME SUB_PROCESS_NAME, 
       SL_NO, PROD_ID, ITEM_NAME, OUTPUT_QTY, OUTPUT_UOM,ACE.ELEMENT_NAME, CONTAINER_NO 
FROM PP_WIP_PROC_OUTPUT PWPO
LEFT JOIN PP_WIP_PROCESS PWP ON PWPO.WIP_PROCESS_ID = PWP.ID
LEFT JOIN PP_PROCESS_CONFIG PPC ON PWP.PROCESS_ID = PPC.ID 
LEFT JOIN PP_PROCESS_CONFIG PPC1 ON  PWP.SUB_PROCESS_ID = PPC1.ID 
LEFT JOIN ADM_CODE_ELEMENTS ACE ON PWPO.OUTPUT_UOM = ACE.ID
WHERE PWP.WIP_MST_ID IN (
SELECT ID FROM PP_WIP_MST WHERE PROD_ID = :pPROD_ID AND BATCH_ID = :pBATCH_ID)
ORDER BY PWP.PROCESS_SEQUENCE;


--6-- PROCESS INPUT ---

SELECT PWPI.ID, WIP_PROCESS_ID,PWP.PROCESS_SEQUENCE PROC_SEQ,PWP.PROCESS_ID,PPC.PROCESS_NAME,PWP.SUB_PROCESS_ID,PPC1.PROCESS_NAME SUB_PROCESS_NAME,
       SL_NO, PROD_ID, ITEM_NAME, INPUT_QTY, INPUT_UOM, INPUT_RATE, INPUT_VALUE
FROM PP_WIP_PROC_INPUT PWPI
LEFT JOIN PP_WIP_PROCESS PWP ON PWPI.WIP_PROCESS_ID = PWP.ID
LEFT JOIN PP_PROCESS_CONFIG PPC ON PWP.PROCESS_ID = PPC.ID 
LEFT JOIN PP_PROCESS_CONFIG PPC1 ON  PWP.SUB_PROCESS_ID = PPC1.ID 
LEFT JOIN ADM_CODE_ELEMENTS ACE ON PWPI.INPUT_UOM = ACE.ID
WHERE PWP.WIP_MST_ID IN (
SELECT ID FROM PP_WIP_MST WHERE PROD_ID = :pPROD_ID AND BATCH_ID = :pBATCH_ID)
ORDER BY PWP.PROCESS_SEQUENCE;

--3-- EMPLOYEE ENGAGE ---

SELECT PWPE.ID, WIP_PROCESS_ID,PWP.PROCESS_SEQUENCE PROC_SEQ,PWP.PROCESS_ID,PPC.PROCESS_NAME,PWP.SUB_PROCESS_ID,PPC1.PROCESS_NAME SUB_PROCESS_NAME, 
       PWPE.PERSON_ID||' - '||HE.EMP_NAME||' ('||(HD.DESIG_NAME)||')' EMPLOYEE,START_TIME, END_TIME, TOTAL_TIME_CONS TOTAL_TIME 
FROM PP_WIP_PROC_EMP PWPE
LEFT JOIN PP_WIP_PROCESS PWP ON PWPE.WIP_PROCESS_ID = PWP.ID
LEFT JOIN PP_PROCESS_CONFIG PPC ON PWP.PROCESS_ID = PPC.ID 
LEFT JOIN PP_PROCESS_CONFIG PPC1 ON  PWP.SUB_PROCESS_ID = PPC1.ID 
LEFT JOIN HRM_EMPLOYEE HE ON PWPE.PERSON_ID=HE.ID
LEFT JOIN HRM_DESIGNATION HD ON HE.DESIGNATION_ID=HD.ID
WHERE PWP.WIP_MST_ID IN (
SELECT ID FROM PP_WIP_MST WHERE PROD_ID = :pPROD_ID AND BATCH_ID = :pBATCH_ID)
ORDER BY PWP.PROCESS_SEQUENCE DESC,PWPE.ID DESC;

--4-- MACHINE ENGAGE ---

SELECT PWPM.ID, WIP_PROCESS_ID,PWP.PROCESS_SEQUENCE PROC_SEQ,PWP.PROCESS_ID,PPC.PROCESS_NAME,PWP.SUB_PROCESS_ID,PPC1.PROCESS_NAME SUB_PROCESS_NAME,
           PWPM.ROOM_ID, ASSET_ID,FAR.ASSET_NAME, START_TIME, END_TIME, TOTAL_TIME_CONS 
FROM PP_WIP_PROC_MACH PWPM
LEFT JOIN PP_WIP_PROCESS PWP ON PWPM.WIP_PROCESS_ID = PWP.ID
LEFT JOIN PP_PROCESS_CONFIG PPC ON PWP.PROCESS_ID = PPC.ID 
LEFT JOIN PP_PROCESS_CONFIG PPC1 ON  PWP.SUB_PROCESS_ID = PPC1.ID 
LEFT JOIN FICO_ASSET_REGISTER FAR ON PWPM.ASSET_ID = FAR.ID
WHERE PWP.WIP_MST_ID IN (
SELECT ID FROM PP_WIP_MST WHERE PROD_ID = :pPROD_ID AND BATCH_ID = :pBATCH_ID)
ORDER BY PWP.PROCESS_SEQUENCE DESC,PWPM.ID DESC;



--7-- PROCESS YIELD ---

SELECT PWPY.ID, WIP_PROCESS_ID,PWP.PROCESS_SEQUENCE PROC_SEQ,PWP.PROCESS_ID,PPC.PROCESS_NAME,PWP.SUB_PROCESS_ID,PPC1.PROCESS_NAME SUB_PROCESS_NAME,
       SL_NO, PREFIX, RECORD_PARAM, RECORD_FORMULA, YIELD_VALUE, YIELD_UOM, YIELD_NOTES 
FROM PP_WIP_PROC_YIELD PWPY
LEFT JOIN PP_WIP_PROCESS PWP ON PWPY.WIP_PROCESS_ID = PWP.ID
LEFT JOIN PP_PROCESS_CONFIG PPC ON PWP.PROCESS_ID = PPC.ID 
LEFT JOIN PP_PROCESS_CONFIG PPC1 ON  PWP.SUB_PROCESS_ID = PPC1.ID 
LEFT JOIN ADM_CODE_ELEMENTS ACE ON PWPY.YIELD_UOM = ACE.ID
WHERE PWP.WIP_MST_ID IN (
SELECT ID FROM PP_WIP_MST WHERE PROD_ID = :pPROD_ID AND BATCH_ID = :pBATCH_ID)
ORDER BY PWP.PROCESS_SEQUENCE;


-------SAMPLE

SELECT PWQS.ID, WIP_PROCESS_ID,PWP.PROCESS_SEQUENCE PROC_SEQ,PWP.PROCESS_ID,PPC.PROCESS_NAME,PWP.SUB_PROCESS_ID,PPC1.PROCESS_NAME SUB_PROCESS_NAME,SAMPLE_QTY
 FROM PP_WIP_QCOM_SAMPLE PWQS
LEFT JOIN PP_WIP_PROCESS PWP ON PWQS.WIP_PROCESS_ID = PWP.ID
LEFT JOIN PP_PROCESS_CONFIG PPC ON PWP.PROCESS_ID = PPC.ID 
LEFT JOIN PP_PROCESS_CONFIG PPC1 ON  PWP.SUB_PROCESS_ID = PPC1.ID 
WHERE PWP.WIP_MST_ID IN (
SELECT ID FROM PP_WIP_MST WHERE PROD_ID = :pPROD_ID AND BATCH_ID = :pBATCH_ID)
ORDER BY PWP.PROCESS_SEQUENCE;

----

SELECT PWM.ID,BATCH_ID,PPB.BATCH_NO FROM PP_WIP_MST PWM
LEFT JOIN PP_PRODUCT_BATCH PPB ON PWM.BATCH_ID = PPB.ID
WHERE PWM.PROD_ID=183
ORDER BY 2;

