
SELECT * FROM PP_QC_SAMPLE_ASSIGN;

--1-->tran_type
SELECT ID,ELEMENT_NAME FROM ADM_CODE_ELEMENTS
WHERE CODE_KEY='QC_TRAN_TYPE'
AND ID IN (SELECT TRANSACTION_TYPE FROM PP_QC_SAMPLE_ASSIGN);

--2-->qc_status
SELECT ID,ELEMENT_NAME FROM ADM_CODE_ELEMENTS 
WHERE ID IN (SELECT QC_STATUS FROM PP_QC_SAMPLE_ASSIGN
             WHERE TRANSACTION_TYPE=:pTrn_Type);


--3
SELECT QSA.ID,TRANSACTION_ID GRN_ID,QSA.LAB_CONTROL_CODE,QSA.PROD_ID,P.PROD_NAME
FROM PP_QC_SAMPLE_ASSIGN QSA
LEFT JOIN ADM_PRODUCTS P ON QSA.PROD_ID=P.ID
WHERE  TRANSACTION_TYPE=:pTrn_Type
AND QSA.QC_STATUS=:pQC_STATUS;

--4
SELECT QSA.ID,TRANSACTION_ID GRN_ID,LAB_CONTROL_CODE,PROD_ID,P.PROD_NAME,ASSIGN_DATE SAMPLING_DATE, DFN_GET_QC_TEST_ANALYZED (QSA.LAB_CONTROL_CODE) ANALYZED_BY 
FROM PP_QC_SAMPLE_ASSIGN QSA
LEFT JOIN ADM_PRODUCTS P ON QSA.PROD_ID=P.ID
WHERE QSA.ID =:pQSA_ID;--ID


--5
SELECT QP.PROD_ID,QPS.ID,QPS.TEST_ID,CE.ELEMENT_NAME TEST_NAME,QPS.SPECIFICATION,QPS.REFERENCE 
FROM PP_QC_PARAM QP
LEFT JOIN PP_QC_PARAM_SPEC QPS ON QP.ID=QPS.QC_PARAM_ID
LEFT JOIN ADM_CODE_ELEMENTS CE ON QPS.TEST_ID=CE.ID
WHERE  QP.PROD_ID=:pPROD_ID;


--6--TEST STATUS
SELECT ID,ELEMENT_NAME FROM ADM_CODE_ELEMENTS
WHERE CODE_KEY = 'QC_TEST_STATUS';




-----QNTY INFO

SELECT A.GRN_QTY,A.GRN_UOM,B.SAMPLE_QTY,B.SMPL_UOM,NVL(A.GRN_QTY,0)-NVL(B.SAMPLE_QTY,0) NET_GRN_QTY FROM (
SELECT SUM(NVL(RCV_QTY,0)) GRN_QTY,JERP_ADM.FD_GET_BASE_UOM(PROD_UOM) GRN_UOM FROM ADM_GRN_DETAIL
WHERE GRN_ID IN (
SELECT ID FROM ADM_GRN
WHERE ID=:pGRN_ID --2838
)
AND PROD_ID=:pPROD_ID --6009
GROUP BY PROD_UOM)A,(
SELECT  SUM(NVL(SAMPLE_QTY,0)) SAMPLE_QTY,JERP_ADM.FD_GET_BASE_UOM(SAMPLE_UOM) SMPL_UOM FROM  PP_QC_SAMPLING
WHERE QC_SAMPLE_ID IN (
SELECT ID FROM PP_QC_SAMPLE_ASSIGN
WHERE TRANSACTION_ID=:pGRN_ID --2838
AND PROD_ID=:pPROD_ID --6009
)
GROUP BY SAMPLE_UOM)B;

--dtl data
SELECT ID, TEST_RESULT_ID, TEST_ID, TEST_NAME, SPECIFICATION, REFERENCE, TEST_RESULT_VALUE, REMARKS 
FROM PP_QC_TEST_DTL
WHERE TEST_RESULT_ID=:PQCTM_ID

--mst data
SELECT ID,TEST_STATUS,PASSED_QTY, HOLD_QTY, REJECT_QTY,RE_TEST_DATE, EXPIRY_DATE,POTENCY,VERIFY_COMMENTS
FROM PP_QC_TEST_MST
WHERE ID=:PQCTM_ID

--json formate
select json_object(
                   'success'        VALUE 'true',
                   'response_code'  VALUE 200,
                   'qty_info'       VALUE (json_object(
                                                       'grn_qty' value l.GRN_QTY,
                                                       'grn_uom' value l.GRN_UOM,
                                                       'sample_qty' value l.SAMPLE_QTY,
                                                       'smpl_uom' value l.SMPL_UOM,
                                                       'net_grn_qty' value l.NET_GRN_QTY
                                                       )
                                           )
                 ) rslt from (
SELECT A.GRN_QTY,A.GRN_UOM,B.SAMPLE_QTY,B.SMPL_UOM,NVL(A.GRN_QTY,0)-NVL(B.SAMPLE_QTY,0) NET_GRN_QTY 
FROM (SELECT SUM(NVL(RCV_QTY,0)) GRN_QTY,JERP_ADM.FD_GET_BASE_UOM(PROD_UOM) GRN_UOM 
      FROM ADM_GRN_DETAIL
      WHERE GRN_ID IN (SELECT ID FROM ADM_GRN WHERE ID=:pGRN_ID)
      AND PROD_ID=:pPROD_ID
      GROUP BY PROD_UOM
     )A,
     (SELECT  SUM(NVL(SAMPLE_QTY,0)) SAMPLE_QTY,JERP_ADM.FD_GET_BASE_UOM(SAMPLE_UOM) SMPL_UOM 
      FROM  PP_QC_SAMPLING
      WHERE QC_SAMPLE_ID IN ( SELECT ID FROM PP_QC_SAMPLE_ASSIGN
                              WHERE TRANSACTION_ID=:pGRN_ID
                              AND PROD_ID=:pPROD_ID
                            )
      GROUP BY SAMPLE_UOM
     )B) l