
--LEFT  PANEL  MATERIAL TYPE FILTER ICON -  1NO API
API TYPE : GET
API NAME: api/pp/get_material_type

Response Fields :  
	 DESCRIPTION,  CAT_NAME
Operational Fields: 
	ID, DESCRIPTION ,
             'RAW - ' || CAT_NAME = CAT_NAME
             'PACKING - ' || CAT_NAME = CAT_NAME
             'BULK - ' || CAT_NAME = CAT_NAME
             'SFG - ' || CAT_NAME = CAT_NAME

PARAMETER :   

Table Name: 
            ADM_PROD_CATEGORY
            
Relation :  
           UNION ALL OF ADM_PROD_CATEGORY TABLE.
  	
Filter by:   
            1. RAW:- PARENT=11 AND LVL=2 AND PROD_TYPE IN(502) 
            2. PACKING:- PARENT=11 AND LVL=2 AND PROD_TYPE IN(503)
            3. BULK:- PARENT=11 AND LVL=2 AND PROD_TYPE IN(514)
            4. SFG:-   PARENT=11 AND LVL=2 AND PROD_TYPE IN(504)
                  
QUERY :  
  
SELECT ID, DESCRIPTION, 'RAW - ' || CAT_NAME AS CAT_NAME
FROM ADM_PROD_CATEGORY WHERE PARENT=25 AND LVL=2 AND PROD_TYPE IN(502)
UNION ALL
SELECT ID, DESCRIPTION, 'PACKING - ' || CAT_NAME AS CAT_NAME
FROM ADM_PROD_CATEGORY WHERE PARENT=25 AND LVL=2 AND PROD_TYPE IN(503)
UNION ALL
SELECT ID, DESCRIPTION, 'MASTER - ' || CAT_NAME AS CAT_NAME
FROM ADM_PROD_CATEGORY WHERE PARENT=25 AND LVL=2 AND PROD_TYPE IN(506)
UNION ALL
SELECT ID, DESCRIPTION, 'SFG - ' || CAT_NAME AS CAT_NAME
FROM ADM_PROD_CATEGORY WHERE PARENT=11 AND LVL=2 AND PROD_TYPE IN(504);


--LEFT SIDE CREATE MODE--API NAME /{pPROD_CAT_ID}
API TYPE : GET
API NAME: api/pp/get-material-list

Response Fields :  
	 DESCRIPTION,  CAT_NAME
Operational Fields: 
	ID, DESCRIPTION ,
             'RAW - ' || CAT_NAME = CAT_NAME
             'PACKING - ' || CAT_NAME = CAT_NAME
             'BULK - ' || CAT_NAME = CAT_NAME
             'SFG - ' || CAT_NAME = CAT_NAME

PARAMETER :   

Table Name: 
            ADM_PROD_CATEGORY
            
Relation :  
           UNION ALL OF ADM_PROD_CATEGORY TABLE.
  	
Filter by:   
           
                  
QUERY :  
  
SELECT AP.ID, AP.PROD_NAME, (CASE WHEN AP.PROD_TYPE IN(502,503) THEN 'RAW-PACK' ELSE 'WIP' END) AS PROD_TYPE_NAME
FROM ADM_PRODUCTS AP JOIN ADM_SBU_PRODUCTS ASP ON AP.ID=ASP.PROD_ID 
WHERE AP.PROD_CAT =: pPROD_CAT_ID   ---SAMPLE -251/ 252/ 271/ 401
AND AP.ID NOT IN(SELECT PROD_ID FROM PP_QC_PARAM);
