--LEFT  PANEL  MATERIAL TYPE FILTER ICON -   1st API
API TYPE : GET
API NAME: api/pp/get_material_type

Response Fields :  
	 DESCRIPTION,  CAT_NAME
Operational Fields: 
	ID, DESCRIPTION ,
             'RAW - ' || CAT_NAME = CAT_NAME
             'PACKING - ' || CAT_NAME = CAT_NAME
             'MASTER - ' || CAT_NAME = CAT_NAME

PARAMETER :   

Table Name: 
            ADM_PROD_CATEGORY
            
Relation :  
           UNION ALL OF ADM_PROD_CATEGORY TABLE.
  	
Filter by:   
            1. RAW:- PARENT=25 AND LVL=2 AND PROD_TYPE IN(502) 
            2. PACKING:- PARENT=25 AND LVL=2 AND PROD_TYPE IN(503)
            3. MASTER:- PARENT=25 AND LVL=2 AND PROD_TYPE IN(506)

                  
QUERY :  
  
SELECT ID, DESCRIPTION, 'RAW - ' || CAT_NAME AS CAT_NAME
FROM ADM_PROD_CATEGORY WHERE PARENT=25 AND LVL=2 AND PROD_TYPE IN(502)
UNION ALL
SELECT ID, DESCRIPTION, 'PACKING - ' || CAT_NAME AS CAT_NAME
FROM ADM_PROD_CATEGORY WHERE PARENT=25 AND LVL=2 AND PROD_TYPE IN(503)
UNION ALL
SELECT ID, DESCRIPTION, 'MASTER - ' || CAT_NAME AS CAT_NAME
FROM ADM_PROD_CATEGORY WHERE PARENT=25 AND LVL=2 AND PROD_TYPE IN(506)


--------------------------------------------------------------
--CREATE MODE--LEFT PANEL LIST-API NAME--AFTER CLICK ON MATERIAL TYPE FILTER ICON FROM LEFT PANEL--2nd API
API TYPE : GET
API NAME: /api/pp/get-material-list/{pPROD_CAT_ID}

Response Fields :  
				AP.ID, AP.PROD_NAME, (CASE WHEN AP.PROD_TYPE IN(502,503) THEN 'RAW-PACK' ELSE 'WIP' END) AS PROD_TYPE_NAME

Operational Fields: 
				AP.ID, AP.PROD_NAME, (CASE WHEN AP.PROD_TYPE IN(502,503) THEN 'RAW-PACK' ELSE 'WIP' END) AS PROD_TYPE_NAME

PARAMETER :   WHERE AP.PROD_CAT =: pPROD_CAT_ID   ---SAMPLE -251/ 252/ 271/ 401

Table Name: 
            ADM_PRODUCTS     =AP
			ADM_SBU_PRODUCTS =ASP
            
Relation :  
           AP.ID=ASP.PROD_ID
  	
Filter by:   

QUERY :  
  
SELECT AP.ID, AP.PROD_NAME, (CASE WHEN AP.PROD_TYPE IN(502,503) THEN 'RAW-PACK' ELSE 'WIP' END) AS PROD_TYPE_NAME
FROM ADM_PRODUCTS AP 
JOIN ADM_SBU_PRODUCTS ASP ON AP.ID=ASP.PROD_ID 
WHERE AP.PROD_CAT =: pPROD_CAT_ID   ---SAMPLE -251/ 252/ 271/ 401
AND AP.ID NOT IN(SELECT PROD_ID FROM PP_QC_PARAM);


--------------------------------------------------------------
--VIEW MODE--LEFT PANEL LIST-API NAME-AFTER CLICK ON MATERIAL TYPE FILTER ICON FROM LEFT PANEL--3rd API
API TYPE : GET
API NAME: api/pp/get-material-list-view-mode/{pPROD_CAT_ID}

Response Fields :  
				AP.ID, AP.PROD_NAME, (CASE WHEN AP.PROD_TYPE IN(502,503) THEN 'RAW-PACK' ELSE 'WIP' END) AS PROD_TYPE_NAME, ACE.ELEMENT_NAME TRAN_STATUS_NAME

Operational Fields: 
				AP.ID, AP.PROD_NAME, (CASE WHEN AP.PROD_TYPE IN(502,503) THEN 'RAW-PACK' ELSE 'WIP' END) AS PROD_TYPE_NAME, QP.ID QC_PARAM_ID,
				QP.TRAN_STATUS, ACE.ELEMENT_NAME TRAN_STATUS_NAME

PARAMETER :   WHERE AP.PROD_CAT =: pPROD_CAT_ID   ---SAMPLE -251/ 252/ 271/ 401

Table Name: 
            ADM_PRODUCTS     =AP
			ADM_SBU_PRODUCTS =ASP
			PP_QC_PARAM      =QP
			ADM_CODE_ELEMENTS =ACE
            
Relation :  
           AP.ID=ASP.PROD_ID
		   AP.ID=QP.PROD_ID
		   QP.TRAN_STATUS=ACE.ID
  	
Filter by:   

QUERY :  

SELECT AP.ID, AP.PROD_NAME, (CASE WHEN AP.PROD_TYPE IN(502,503) THEN 'RAW-PACK' ELSE 'WIP' END) AS PROD_TYPE_NAME, QP.ID QC_PARAM_ID, QP.TRAN_STATUS, ACE.ELEMENT_NAME TRAN_STATUS_NAME
FROM ADM_PRODUCTS AP 
JOIN ADM_SBU_PRODUCTS ASP ON AP.ID=ASP.PROD_ID 
JOIN PP_QC_PARAM QP ON AP.ID=QP.PROD_ID
LEFT JOIN ADM_CODE_ELEMENTS ACE ON QP.TRAN_STATUS=ACE.ID
WHERE AP.PROD_CAT =: pPROD_CAT_ID    ---SAMPLE -251/ 252/ 271/ 401

-----------------------------------------------------------------------------
----LEFT PANEL LIST ID CLICK-VIEW MODE--BASIC INFO(PRIMARY INFO AND PACKAGING INFO)--4th API
API TYPE : GET
API NAME: api/pp/get-qc-param-basic-info/{P_QC_PARAM_ID}

Response Fields :  
				AP.PROD_NAME, QP.SPEC_REF_NO, QP.METHOD_REF_NO, QP.CAS_NO, QP.SYNONYMS, QP.SAFETY_PRE_CAUTION, QP.SHELF_LIFE, ---BASIC INFO
				QP.REFERENCE_NO, QP.DAR_NO, QP.DESCRIPTION, QP.SHAPE_SIZE, QP.COLOR_SMELL, QP.TRAN_STATUS, ACE.ELEMENT_NAME TRAN_STATUS_NAME, QP.SUPERSEDES, QP.MOLECULAR_FORMULA, QP.MOLECULAR_WEIGHT, QP.EFFECTIVE_DATE, --BASIC INFO 
				QP.PACK_SIZE, QP.PACKING_MODE, QP.CONTAINER, QP.STORAGE_CONDITION, QP.DOC_COM_SUPP, QP.DOC_NEW_SOURCE, QP.LABEL_INFO --PACKAGING INFO
				
Operational Fields: 
				QP.ID PARAM_ID, QP.PROD_ID, AP.PROD_NAME, QP.SPEC_REF_NO, QP.METHOD_REF_NO, QP.CAS_NO, QP.SYNONYMS, QP.SAFETY_PRE_CAUTION, QP.SHELF_LIFE, ---BASIC INFO
				QP.REFERENCE_NO, QP.DAR_NO, QP.DESCRIPTION, QP.SHAPE_SIZE, QP.COLOR_SMELL, QP.TRAN_STATUS, ACE.ELEMENT_NAME TRAN_STATUS_NAME, QP.SUPERSEDES, QP.MOLECULAR_FORMULA, QP.MOLECULAR_WEIGHT, QP.EFFECTIVE_DATE, --BASIC INFO 
				QP.PACK_SIZE, QP.PACKING_MODE, QP.CONTAINER, QP.STORAGE_CONDITION, QP.DOC_COM_SUPP, QP.DOC_NEW_SOURCE, QP.LABEL_INFO, --PACKAGING INFO
				QP.STATUS

PARAMETER :   WHERE QP.ID= :P_QC_PARAM_ID  --10041

Table Name: 
            PP_QC_PARAM       =QP
			ADM_PRODUCTS      =AP
			ADM_CODE_ELEMENTS =ACE
            
Relation :  
           QP.PROD_ID=AP.ID
		   QP.TRAN_STATUS=ACE.ID
  	
Filter by:   

QUERY :  

SELECT QP.ID PARAM_ID, QP.PROD_ID, AP.PROD_NAME, QP.SPEC_REF_NO, QP.METHOD_REF_NO, QP.CAS_NO, QP.SYNONYMS, QP.SAFETY_PRE_CAUTION, QP.SHELF_LIFE, ---BASIC INFO
QP.REFERENCE_NO, QP.DAR_NO, QP.DESCRIPTION, QP.SHAPE_SIZE, QP.COLOR_SMELL, QP.TRAN_STATUS, ACE.ELEMENT_NAME TRAN_STATUS_NAME, QP.SUPERSEDES, QP.MOLECULAR_FORMULA, QP.MOLECULAR_WEIGHT, QP.EFFECTIVE_DATE, --BASIC INFO 
QP.PACK_SIZE, QP.PACKING_MODE, QP.CONTAINER, QP.STORAGE_CONDITION, QP.DOC_COM_SUPP, QP.DOC_NEW_SOURCE, QP.LABEL_INFO, --PACKAGING INFO
QP.STATUS
FROM PP_QC_PARAM QP
JOIN ADM_PRODUCTS AP ON QP.PROD_ID=AP.ID
LEFT JOIN ADM_CODE_ELEMENTS ACE ON QP.TRAN_STATUS=ACE.ID
WHERE QP.ID= :P_QC_PARAM_ID; --10041

---------------------------------------------------------------------
----LEFT PANEL LIST ID CLICK-VIEW MODE--BASIC INFO(REVISION PART)--5th API
API TYPE : GET
API NAME: api/pp/get-qc-param-revision-info/{P_QC_PARAM_ID}

Response Fields :  
				QP.ISSUE_DATE, QP.REVIEW_DATE, QP.VERSION_NO, QP.CAUSE_FOR_VERSION --REVISION INFO
				
Operational Fields: 
				QP.ISSUE_DATE, QP.REVIEW_DATE, QP.VERSION_NO, QP.CAUSE_FOR_VERSION --REVISION INFO

PARAMETER :   ID= :P_QC_PARAM_ID --10041

Table Name: 
            PP_QC_PARAM       =QP
			ADM_PRODUCTS      =AP
			ADM_CODE_ELEMENTS =ACE
            
Relation :  
           QP.PROD_ID=AP.ID
		   QP.TRAN_STATUS=ACE.ID
  	
Filter by:   

QUERY :  


------REVISION PART

SELECT QP.ISSUE_DATE, QP.REVIEW_DATE, QP.VERSION_NO, QP.CAUSE_FOR_VERSION --REVISION INFO
FROM PP_QC_PARAM QP
JOIN ADM_PRODUCTS AP ON QP.PROD_ID=AP.ID
LEFT JOIN ADM_CODE_ELEMENTS ACE ON QP.TRAN_STATUS=ACE.ID
WHERE QP.PROD_ID IN (SELECT PROD_ID FROM PP_QC_PARAM WHERE ID= :P_QC_PARAM_ID ) --10041

---------------------------------------------



--RIGHT PANEL  BODY -   - 6th API--NEEDS MODIFICATION
API TYPE : GET
API NAME : api/pp/get-test-spec-data/{pQC_PARAM_ID}/{pQC_PARAM_PROCESS_ID}

Response Fields :  
	  PS.TEST_SERIAL_NO, PS.TEST_ID, AC.ELEMENT_NAME = TEST_NAME, AC.ELEMENT_NAME = TEST_TYPE_NAME, PS.SPECIFICATION
	  
Operational Fields: 
	PS.ID, PS.QC_PARAM_ID, PS.VERSION_NO, PS.TEST_TYPE, AC.ELEMENT_NAME = TEST_TYPE_NAME, PS.TEST_ID, AC.ELEMENT_NAME = TEST_NAME, 
	PS.SPECIFICATION, PS.TEST_SERIAL_NO, PS.SORT_ORDER, PS.STATUS, 
    PS.CREATED_BY, PS.CREATED_AT, PS.UPDATED_BY, PS.UPDATED_AT, PS.QC_PARAM_PROCESS_ID
    
PARAMETER : PS.QC_PARAM_ID = :pQC_PARAM_ID AND PS.QC_PARAM_PROCESS_ID = :pQC_PARAM_PROCESS_ID

Table Name: 
            PP_QC_PARAM_SPEC = PS
            ADM_CODE_ELEMENTS = AC         
            ADM_CODE_ELEMENTS = ACC  
             
            
Relation :  
            PS.TEST_TYPE=AC.ID
             PS.TEST_ID=ACC.ID
              
  
Filter by:   
            
                  
QUERY :  

SELECT PS.ID, PS.QC_PARAM_ID, PS.VERSION_NO, PS.TEST_TYPE, AC.ELEMENT_NAME AS TEST_TYPE_NAME, PS.TEST_ID, PQIT.TEST_NAME, PS.SPECIFICATION, PS.TEST_SERIAL_NO, PS.SORT_ORDER, PS.STATUS, 
PS.CREATED_BY, PS.CREATED_AT, PS.UPDATED_BY, PS.UPDATED_AT, PS.QC_PARAM_PROCESS_ID
FROM PP_QC_PARAM_SPEC PS
JOIN ADM_CODE_ELEMENTS AC ON PS.TEST_TYPE=AC.ID
JOIN PP_QC_IPQC_TEST PQIT ON PS.TEST_ID=PQIT.ID
WHERE PS.QC_PARAM_ID = :pQC_PARAM_ID --10047
AND PS.QC_PARAM_PROCESS_ID = :pQC_PARAM_PROCESS_ID  --10058
ORDER BY TEST_SERIAL_NO

--OLD QRY
/*  
SELECT PS.ID, PS.QC_PARAM_ID, PS.VERSION_NO, PS.TEST_TYPE, AC.ELEMENT_NAME AS TEST_TYPE_NAME, PS.TEST_ID, ACC.ELEMENT_NAME AS TEST_NAME, PS.SPECIFICATION, PS.TEST_SERIAL_NO, PS.SORT_ORDER, PS.STATUS, 
PS.CREATED_BY, PS.CREATED_AT, PS.UPDATED_BY, PS.UPDATED_AT, PS.QC_PARAM_PROCESS_ID
FROM PP_QC_PARAM_SPEC PS
JOIN ADM_CODE_ELEMENTS AC ON PS.TEST_TYPE=AC.ID
JOIN ADM_CODE_ELEMENTS ACC ON PS.TEST_ID=ACC.ID
WHERE PS.QC_PARAM_ID = :pQC_PARAM_ID --10047
AND PS.QC_PARAM_PROCESS_ID is null--= :pQC_PARAM_PROCESS_ID  --10058
ORDER BY TEST_SERIAL_NO
*/

--2 COLUMN WILL BE REMOVED --PS.VALUE_RANGE, PS.MEAN_OF_RESULT
--1 NEW COLUMN WILL BE ADDED--PS.TEST_SERIAL_NO

-----------------------------------


--AFTER SELECTING ICON ON TEST NAME OF QC SPEC---NEW API
API TYPE : GET
API NAME : api/pp/get-qc-spec-attribute

Response Fields :  
                    AT.ATTRIBUTE_NAME, AT.DATA_TYPE, ATT.DISPLAY_NAME
	  
Operational Fields: 
                AT.ID, AT.ATTRIBUTE_NAME, AT.DATA_TYPE, AC.ELEMENT_NAME, ATT.TABLE_NAME, ATT.DISPLAY_NAME, ATT.ID ATTRIBUTE_ID, ATT.SORT_ORDER
         
PARAMETER  : 

Table Name:   	ADM_ATTRIBUTES 	   =AT
                ADM_CODE_ELEMENTS  =AC
                ADM_ATTRIBUTES_TAB =ATT


Relation : 	  	AT.DATA_TYPE=AC.ID
                AT.ID=ATT.ATTRIBUTE_ID
    
Filter by:  WHERE ATT.TABLE_NAME='PP_QC_PARAM_SPEC'


QUERY : 

SELECT AT.ID, AT.ATTRIBUTE_NAME, AT.DATA_TYPE, AC.ELEMENT_NAME, ATT.TABLE_NAME, ATT.DISPLAY_NAME, ATT.ID ATTRIBUTE_ID, ATT.SORT_ORDER
FROM ADM_ATTRIBUTES AT JOIN ADM_CODE_ELEMENTS AC ON AT.DATA_TYPE=AC.ID 
JOIN ADM_ATTRIBUTES_TAB ATT ON AT.ID=ATT.ATTRIBUTE_ID
WHERE ATT.TABLE_NAME='PP_QC_PARAM_SPEC'


--------------------------------------------
--VIEW ATTRIBUTE DATA FROM QC SPEC ROW---NEW API
API TYPE : GET
API NAME : api/pp/get-qc-spec-att-data/{pDATA_ROW_ID}

Response Fields :  
                    ATT.ID ATTRIBUTE_ID, AT.ATTRIBUTE_NAME, ATT.DISPLAY_NAME, ATD.DATA_VALUE, ATD.ID
	  
Operational Fields: 
                ATT.ID ATTRIBUTE_ID, AT.ATTRIBUTE_NAME, ATT.DISPLAY_NAME, ATD.DATA_VALUE, ATD.ID
         
PARAMETER  : 	ATD.DATA_ROW_ID  = :pDATA_ROW_ID  (COME FROM 1ST API-->ATD.DATA_ROW_ID)  --10149

Table Name:   	ADM_ATTRIBUTES_TAB      =ATT
                ADM_ATTRIBUTES          =AT
                ADM_ATTRIBUTES_TAB_DATA =ATD


Relation : 	  	ATT.ATTRIBUTE_ID=AT.ID
			ATT.ID=ATD.ATAB_ID
    
Filter by:  WHERE ATT.TABLE_NAME='PP_QC_PARAM_SPEC' 


QUERY : 

SELECT ATT.ID ATTRIBUTE_ID, AT.ATTRIBUTE_NAME, ATT.DISPLAY_NAME, ATD.DATA_VALUE, ATD.ID
FROM ADM_ATTRIBUTES_TAB ATT
JOIN ADM_ATTRIBUTES AT ON ATT.ATTRIBUTE_ID=AT.ID
JOIN ADM_ATTRIBUTES_TAB_DATA ATD ON ATT.ID=ATD.ATAB_ID
WHERE ATT.TABLE_NAME='PP_QC_PARAM_SPEC' AND ATD.DATA_ROW_ID=:pDATA_ROW_ID  ---10149


------------------------------