---1no -- left panel filter data

SELECT ID, DESCRIPTION, 'RAW - ' || CAT_NAME AS CAT_NAME
FROM ADM_PROD_CATEGORY WHERE PARENT=25 AND LVL=2 AND PROD_TYPE IN(502)
UNION ALL
SELECT ID, DESCRIPTION, 'PACKING - ' || CAT_NAME AS CAT_NAME
FROM ADM_PROD_CATEGORY WHERE PARENT=25 AND LVL=2 AND PROD_TYPE IN(503)
UNION ALL
SELECT ID, DESCRIPTION, 'MASTER - ' || CAT_NAME AS CAT_NAME
FROM ADM_PROD_CATEGORY WHERE PARENT=25 AND LVL=2 AND PROD_TYPE IN(506)
UNION ALL
SELECT ID, DESCRIPTION, 'SFG - ' || CAT_NAME AS CAT_NAME
FROM ADM_PROD_CATEGORY WHERE PARENT=11 AND LVL=2 AND PROD_TYPE IN(504)


---2no

--CREATE MODE--API NAME -/api/pp/get-material-list/{pPROD_CAT_ID}

SELECT AP.ID, AP.PROD_NAME, (CASE WHEN AP.PROD_TYPE IN(502,503) THEN 'RAW-PACK' ELSE 'WIP' END) AS PROD_TYPE_NAME
FROM ADM_PRODUCTS AP JOIN ADM_SBU_PRODUCTS ASP ON AP.ID=ASP.PROD_ID 
WHERE AP.PROD_CAT =: pPROD_CAT_ID   ---SAMPLE -251/ 252/ 271/ 401
AND AP.ID NOT IN(SELECT PROD_ID FROM PP_QC_PARAM);

---VIEW MODE--API NAME - /api/pp/get-material-list-view-mode/{pPROD_CAT_ID}

SELECT AP.ID, AP.PROD_NAME, (CASE WHEN AP.PROD_TYPE IN(502,503) THEN 'RAW-PACK' ELSE 'WIP' END) AS PROD_TYPE_NAME, QP.ID QC_PARAM_ID, QP.TRAN_STATUS, ACE.ELEMENT_NAME TRAN_STATUS_NAME
FROM ADM_PRODUCTS AP JOIN ADM_SBU_PRODUCTS ASP ON AP.ID=ASP.PROD_ID 
JOIN PP_QC_PARAM QP ON AP.ID=QP.PROD_ID
LEFT JOIN ADM_CODE_ELEMENTS ACE ON QP.TRAN_STATUS=ACE.ID
WHERE AP.PROD_CAT =: pPROD_CAT_ID    ---SAMPLE -251/ 252/ 271/ 401


----3NO --MASTER INFO (BASICK INFO)

SELECT QP.ID PARAM_ID, QP.PROD_ID, AP.PROD_NAME, QP.SPEC_REF_NO, QP.METHOD_REF_NO, QP.CAS_NO, QP.SYNONYMS, QP.SAFETY_PRE_CAUTION, QP.SHELF_LIFE, ---BASIC INFO
QP.REFERENCE_NO, QP.DAR_NO, QP.DESCRIPTION, QP.SHAPE_SIZE, QP.COLOR_SMELL, QP.TRAN_STATUS, ACE.ELEMENT_NAME TRAN_STATUS_NAME, QP.SUPERSEDES, QP.MOLECULAR_FORMULA, QP.MOLECULAR_WEIGHT, QP.EFFECTIVE_DATE, --BASIC INFO 
QP.PACK_SIZE, QP.PACKING_MODE, QP.CONTAINER, QP.STORAGE_CONDITION, QP.DOC_COM_SUPP, QP.DOC_NEW_SOURCE, QP.LABEL_INFO, --PACKAGING INFO
QP.STATUS
FROM PP_QC_PARAM QP
JOIN ADM_PRODUCTS AP ON QP.PROD_ID=AP.ID
LEFT JOIN ADM_CODE_ELEMENTS ACE ON QP.TRAN_STATUS=ACE.ID
WHERE QP.ID= :P_QC_PARAM_ID; --10041


------REVISION PART

SELECT QP.ISSUE_DATE, QP.REVIEW_DATE, QP.VERSION_NO, QP.CAUSE_FOR_VERSION --REVISION INFO
FROM PP_QC_PARAM QP
JOIN ADM_PRODUCTS AP ON QP.PROD_ID=AP.ID
LEFT JOIN ADM_CODE_ELEMENTS ACE ON QP.TRAN_STATUS=ACE.ID
WHERE QP.PROD_ID IN (SELECT PROD_ID FROM PP_QC_PARAM WHERE ID= :P_QC_PARAM_ID ); --10041


--version list  {P_PROD_ID}

SELECT VERSION_NO 
FROM PP_QC_PARAM
WHERE PROD_ID= :P_PROD_ID; --COME FROM 2NO API



-----QC SPEC DETAILS INFO-FOR RAW/PACK MATERIAL----------

SELECT QP.ID PARAM_ID, QP.PROD_ID, AP.PROD_NAME, QS.VERSION_NO, QS.ID SPEC_ID, QS.TEST_SERIAL_NO, QS.TEST_ID, ACE.ELEMENT_NAME TEST_NAME, 
QS.SPECIFICATION, QS.TEST_TYPE, AC.ELEMENT_NAME TEST_TYPE_NAME, QS.REFERENCE
FROM PP_QC_PARAM QP
JOIN ADM_PRODUCTS AP ON QP.PROD_ID=AP.ID
JOIN PP_QC_PARAM_SPEC QS ON QP.ID= QS.QC_PARAM_ID
LEFT JOIN ADM_CODE_ELEMENTS ACE ON QS.TEST_ID=ACE.ID
LEFT JOIN ADM_CODE_ELEMENTS AC ON QS.TEST_TYPE=AC.ID
WHERE QS.QC_PARAM_PROCESS_ID IS NULL
AND QP.ID = :P_QC_PARAM_ID;


-----QC SPEC DETAILS INFO-FOR WIP MATERIALS------------

SELECT QP.ID PARAM_ID, QP.PROD_ID, AP.PROD_NAME, PP.WIP_STAGE_ID,  PP.PROCESS_ID,  PP.SUB_PROCESS_ID, PP.IS_IPQC ,
QS.VERSION_NO,QS.ID SPEC_ID, QS.TEST_SERIAL_NO, QS.TEST_ID,  QS.SPECIFICATION, QS.TEST_TYPE,  QS.REFERENCE,
ACE.ELEMENT_NAME TEST_NAME,AC.ELEMENT_NAME TEST_TYPE_NAME,AC1.ELEMENT_NAME WIP_STAGE_NAME,PC.PROCESS_NAME,PC1.PROCESS_NAME SUB_PROCESS_NAME
FROM PP_QC_PARAM QP
JOIN ADM_PRODUCTS AP ON QP.PROD_ID=AP.ID
JOIN PP_QC_PARAM_PROCESS PP ON QP.ID=PP.QC_PARAM_ID 
JOIN PP_QC_PARAM_SPEC QS ON QP.ID= QS.QC_PARAM_ID AND PP.ID=QS.QC_PARAM_PROCESS_ID
LEFT JOIN ADM_CODE_ELEMENTS ACE ON QS.TEST_ID=ACE.ID
LEFT JOIN ADM_CODE_ELEMENTS AC ON QS.TEST_TYPE=AC.ID
LEFT JOIN ADM_CODE_ELEMENTS AC1 ON PP.WIP_STAGE_ID=AC1.ID
LEFT JOIN PP_PROCESS_CONFIG PC ON PP.PROCESS_ID=PC.ID
LEFT JOIN PP_PROCESS_CONFIG PC1 ON PP.SUB_PROCESS_ID=PC1.ID
WHERE QS.QC_PARAM_PROCESS_ID IS NOT NULL
AND QP.ID = :P_QC_PARAM_ID;


---right panel QC_SPEC TAb er left panel data (CREATE MODE) FOR WIP

SELECT PPT.PROD_ID, PTP.WIP_STAGE_ID, AC.ELEMENT_NAME, PTP.PROCESS_ID, PC.PROCESS_NAME, PTP.SUB_PROCESS_ID, PCC.PROCESS_NAME AS SUB_PROCESS_NAME
FROM PP_PROD_PROC_TYPE PPT 
JOIN PP_PROC_TYPE_PROCESS PTP ON PPT.ID=PTP.PROD_PROC_TYPE_ID
LEFT JOIN ADM_CODE_ELEMENTS AC ON PTP.WIP_STAGE_ID=AC.ID
LEFT JOIN PP_PROCESS_CONFIG PC ON PTP.PROCESS_ID=PC.ID
LEFT JOIN PP_PROCESS_CONFIG PCC ON PTP.SUB_PROCESS_ID=PCC.ID
WHERE PTP.QC_REQUIRED='Y' AND WIP_STAGE_ID IS NOT NULL
AND PPT.PROD_ID = :pPRODUCTID; --4001

---right panel IPQC_SPEC TAb er left panel data (CREATE MODE) WIP

SELECT PPT.PROD_ID, PTP.WIP_STAGE_ID, AC.ELEMENT_NAME, PTP.PROCESS_ID, PC.PROCESS_NAME, PTP.SUB_PROCESS_ID, PCC.PROCESS_NAME AS SUB_PROCESS_NAME
FROM PP_PROD_PROC_TYPE PPT 
JOIN PP_PROC_TYPE_PROCESS PTP ON PPT.ID=PTP.PROD_PROC_TYPE_ID
LEFT JOIN ADM_CODE_ELEMENTS AC ON PTP.WIP_STAGE_ID=AC.ID
LEFT JOIN PP_PROCESS_CONFIG PC ON PTP.PROCESS_ID=PC.ID
LEFT JOIN PP_PROCESS_CONFIG PCC ON PTP.SUB_PROCESS_ID=PCC.ID
WHERE PTP.QC_REQUIRED='Y' 
AND PPT.PROD_ID = :pPRODUCTID; --4001


---ATTRIBUTE LIST

SELECT ATT.ID ATTRIBUTE_ID, AT.ATTRIBUTE_NAME,ATT.DISPLAY_NAME,ATD.DATA_VALUE, ATD.ID, 
QS.ID QC_SPEC_ID, QS.TEST_ID, ACE.ELEMENT_NAME TEST_NAME
FROM ADM_ATTRIBUTES_TAB ATT
JOIN ADM_ATTRIBUTES AT ON ATT.ATTRIBUTE_ID=AT.ID
JOIN ADM_ATTRIBUTES_TAB_DATA ATD ON ATT.ID=ATD.ATAB_ID
JOIN PP_QC_PARAM_SPEC QS ON ATD.DATA_ROW_ID=QS.ID
JOIN ADM_CODE_ELEMENTS ACE ON QS.TEST_ID=ACE.ID
WHERE ATT.TABLE_NAME='PP_QC_PARAM_SPEC'
