
---PRODUCT PROCESS DETAILS--------------------
SELECT PT.ID PROD_PROC_ID, PT.PROD_ID, AP.PROD_NAME, PT.BATCH_CATEGORY, AC.ELEMENT_NAME BATCH_CATEGORY_NAME, PT.PROCESS_TYPE, AC1.ELEMENT_NAME PROCESS_TYPE_NAME, 
PT.BOM_DISPLAY_CODE, PT.TRAN_STATUS, AC2.ELEMENT_NAME TRAN_STATUS_NAME, TP.ID PROCESS_ROW_ID, TP.PROCESS_ID, PC.PROCESS_NAME, TP.SUB_PROCESS_ID, PC1.PROCESS_NAME SUB_PROCESS_NAME, 
TP.PROCESS_SEQUENCE, TP.IS_MACHINE_GROUP, TP.WIP_STAGE_ID, AC3.ELEMENT_NAME WIP_STAGE_NAME, TP.IPQC_REQUIRED, TP.QC_REQUIRED, TP.RECONCILIATION_REQUIRED, 
TP.TOTAL_PROCESS_TIME, TP.DOC_ID, PM.ID MACHINE_ROW_ID ,PM.MACHINE_ID, FAR.ASSET_NAME
FROM PP_PROD_PROC_TYPE PT JOIN PP_PROC_TYPE_PROCESS TP ON PT.ID=TP.PROD_PROC_TYPE_ID
LEFT JOIN PP_PROCESS_MACHINE PM ON TP.ID=PM.PROC_TYPE_PROCESS_ID
JOIN ADM_PRODUCTS AP ON PT.PROD_ID=AP.ID
LEFT JOIN ADM_CODE_ELEMENTS AC ON PT.BATCH_CATEGORY=AC.ID
LEFT JOIN ADM_CODE_ELEMENTS AC1 ON PT.PROCESS_TYPE=AC1.ID
LEFT JOIN ADM_CODE_ELEMENTS AC2 ON PT.TRAN_STATUS=AC2.ID
LEFT JOIN PP_PROCESS_CONFIG PC ON TP.PROCESS_ID=PC.ID
LEFT JOIN PP_PROCESS_CONFIG PC1 ON TP.SUB_PROCESS_ID=PC1.ID
LEFT JOIN ADM_CODE_ELEMENTS AC3 ON TP.WIP_STAGE_ID=AC3.ID
LEFT JOIN FICO_ASSET_REGISTER FAR ON PM.MACHINE_ID=FAR.ID
--WHERE PT.PROD_ID=4001
ORDER BY TP.PROCESS_SEQUENCE;


SELECT PPTP.PROCESS_ID,PPC.PROCESS_NAME,PPTP.SUB_PROCESS_ID,PPC1.PROCESS_NAME AS SUB_PROCESS_NAME,PPTP.WIP_STAGE_ID,ACE.ELEMENT_NAME,
PPTP.IPQC_REQUIRED, PPTP.QC_REQUIRED, PPTP.RECONCILIATION_REQUIRED,PPTP.TOTAL_PROCESS_TIME,PPTP.IS_MACHINE_GROUP
FROM PP_PROD_PROC_TYPE PPPT
LEFT JOIN PP_PROC_TYPE_PROCESS  PPTP ON PPTP.PROD_PROC_TYPE_ID = PPPT.ID
LEFT JOIN PP_PROCESS_CONFIG PPC ON PPC.ID = PPTP.PROCESS_ID
LEFT JOIN PP_PROCESS_CONFIG PPC1 ON PPC1.ID = PPTP.SUB_PROCESS_ID
LEFT JOIN ADM_CODE_ELEMENTS ACE ON ACE.ID = PPTP.WIP_STAGE_ID
WHERE PPPT.PROD_ID = :pPROD_ID
AND PPPT.SBU_ID = :pSBU_ID
AND PPTP.WIP_STAGE_ID = 7611; -- WIP-BULK AND 7622 -- WIP-SEMI-FINISHED


--
SELECT PPTP.PROCESS_ID,PPC.PROCESS_NAME,PPTP.SUB_PROCESS_ID,PPC1.PROCESS_NAME AS SUB_PROCESS_NAME,PPTP.WIP_STAGE_ID,ACE.ELEMENT_NAME,
PPTP.IPQC_REQUIRED, PPTP.QC_REQUIRED, PPTP.RECONCILIATION_REQUIRED,PPTP.TOTAL_PROCESS_TIME,PPTP.IS_MACHINE_GROUP--,PPM.ID
FROM PP_PROD_PROC_TYPE PPPT
LEFT JOIN PP_PROC_TYPE_PROCESS  PPTP ON PPTP.PROD_PROC_TYPE_ID = PPPT.ID
LEFT JOIN PP_PROCESS_CONFIG PPC ON PPC.ID = PPTP.PROCESS_ID
LEFT JOIN PP_PROCESS_CONFIG PPC1 ON PPC1.ID = PPTP.SUB_PROCESS_ID
LEFT JOIN ADM_CODE_ELEMENTS ACE ON ACE.ID = PPTP.WIP_STAGE_ID
--LEFT JOIN PP_PROCESS_MACHINE PPM ON PPTP.ID = PPM.PROC_TYPE_PROCESS_ID
WHERE PPPT.PROD_ID = :pPROD_ID
AND PPPT.SBU_ID = :pSBU_ID
AND PPTP.WIP_STAGE_ID = 7611 -- WIP-BULK AND 7622 -- WIP-SEMI-FINISHED
GROUP BY PPTP.PROCESS_ID,PPC.PROCESS_NAME,PPTP.SUB_PROCESS_ID,PPC1.PROCESS_NAME,PPTP.WIP_STAGE_ID,ACE.ELEMENT_NAME,
PPTP.IPQC_REQUIRED, PPTP.QC_REQUIRED, PPTP.RECONCILIATION_REQUIRED,PPTP.TOTAL_PROCESS_TIME,PPTP.IS_MACHINE_GROUP--,PPM.ID

---WITH MACHINE

SELECT PPTP.PROCESS_ID,PPC.PROCESS_NAME,PPTP.SUB_PROCESS_ID,PPC1.PROCESS_NAME AS SUB_PROCESS_NAME,PPTP.WIP_STAGE_ID,ACE.ELEMENT_NAME,
PPTP.IPQC_REQUIRED, PPTP.QC_REQUIRED, PPTP.RECONCILIATION_REQUIRED,PPTP.TOTAL_PROCESS_TIME,PPTP.IS_MACHINE_GROUP,PPM.MACHINE_ID
FROM PP_PROD_PROC_TYPE PPPT
LEFT JOIN PP_PROC_TYPE_PROCESS  PPTP ON PPTP.PROD_PROC_TYPE_ID = PPPT.ID
LEFT JOIN PP_PROCESS_CONFIG PPC ON PPC.ID = PPTP.PROCESS_ID
LEFT JOIN PP_PROCESS_CONFIG PPC1 ON PPC1.ID = PPTP.SUB_PROCESS_ID
LEFT JOIN ADM_CODE_ELEMENTS ACE ON ACE.ID = PPTP.WIP_STAGE_ID
LEFT JOIN PP_PROCESS_MACHINE PPM ON PPM.PROC_TYPE_PROCESS_ID = PPTP.ID
WHERE PPPT.PROD_ID = :pPROD_ID
AND PPPT.SBU_ID = :pSBU_ID
AND PPTP.WIP_STAGE_ID = 7611
GROUP BY PPTP.PROCESS_ID,PPC.PROCESS_NAME,PPTP.SUB_PROCESS_ID,PPC1.PROCESS_NAME ,PPTP.WIP_STAGE_ID,ACE.ELEMENT_NAME,
PPTP.IPQC_REQUIRED, PPTP.QC_REQUIRED, PPTP.RECONCILIATION_REQUIRED,PPTP.TOTAL_PROCESS_TIME,PPTP.IS_MACHINE_GROUP,PPM.MACHINE_ID;