
API TYPE : GET
API NAME : api/pp/get-bmr-info-data/{pBOM_ID}

Response Fields :   EFFECTIVE_DATE,CORE_WEIGHT, CORE_UOM, CORE_UOM_DESC, COATED_WEIGHT, 
                    COATED_UOM, COATED_UOM_DESC, CHANGE_HISTORY, REVISION_NO, FILL_WEIGHT, FILL_WEIGHT_UOM, FILL_WEIGHT_UOM_DESC, FILL_VOLUME, 
                    FILL_VOL_UOM, FILL_VOL_UOM_DESC, DESCRIPTION, OTHER_INFO, LABEL_CLAIM, SIZE_SHAPE
	  
Operational Fields: PROD_ID, BMR_ID, EFFECTIVE_DATE, BOM_ID, CORE_WEIGHT, CORE_UOM, CORE_UOM_DESC, COATED_WEIGHT, 
                    COATED_UOM, COATED_UOM_DESC, CHANGE_HISTORY, REVISION_NO, FILL_WEIGHT, FILL_WEIGHT_UOM, FILL_WEIGHT_UOM_DESC, FILL_VOLUME, 
                    FILL_VOL_UOM, FILL_VOL_UOM_DESC, DESCRIPTION, OTHER_INFO, LABEL_CLAIM, SIZE_SHAPE

PARAMETER  : BOM_ID = :pBOM_ID

Table Name: PP_BMR_MASTER 

Relation : 	
    
Filter by:  WHERE  STATUS = 1 

QUERY : 

SELECT PROD_ID,ID BMR_ID,EFFECTIVE_DATE, BOM_ID,CORE_WEIGHT, CORE_UOM,JERP_ADM.FD_GET_BASE_UOM(CORE_UOM) CORE_UOM_DESC, 
COATED_WEIGHT,COATED_UOM,JERP_ADM.FD_GET_BASE_UOM(COATED_UOM) COATED_UOM_DESC,CHANGE_HISTORY, REVISION_NO,FILL_WEIGHT,
FILL_WEIGHT_UOM,JERP_ADM.FD_GET_BASE_UOM(COATED_UOM) FILL_WEIGHT_UOM_DESC, FILL_VOLUME, FILL_VOL_UOM,
JERP_ADM.FD_GET_BASE_UOM(COATED_UOM) FILL_VOL_UOM_DESC, DESCRIPTION, OTHER_INFO, LABEL_CLAIM, SIZE_SHAPE 
FROM PP_BMR_MASTER
WHERE BOM_ID = :pBOM_ID --1264