
GET BMR PROCESS INFO DATA  
API TYPE : GET
API NAME : api/pp/get-bmr-process-data

Response Fields :  

        PPTP.PROCESS_ID,PPC.PROCESS_NAME,PPTP.SUB_PROCESS_ID,PPC1.PROCESS_NAME AS SUB_PROCESS_NAME,PPTP.WIP_STAGE_ID,ACE.ELEMENT_NAME,
        PPTP.IPQC_REQUIRED, PPTP.QC_REQUIRED, PPTP.RECONCILIATION_REQUIRED,PPTP.TOTAL_PROCESS_TIME,PPTP.IS_MACHINE_GROUP
	  
Operational Fields: 
		PPTP.PROCESS_ID,PPC.PROCESS_NAME,PPTP.SUB_PROCESS_ID,PPC1.PROCESS_NAME AS SUB_PROCESS_NAME,PPTP.WIP_STAGE_ID,ACE.ELEMENT_NAME,
        PPTP.IPQC_REQUIRED, PPTP.QC_REQUIRED, PPTP.RECONCILIATION_REQUIRED,PPTP.TOTAL_PROCESS_TIME,PPTP.IS_MACHINE_GROUP
         
PARAMETER  : WHERE PPPT.PROD_ID = :pPROD_ID 
             AND PPPT.SBU_ID = :pSBU_ID

Table Name:   PP_PROD_PROC_TYPE = PPPT
			  PP_PROC_TYPE_PROCESS  = PPTP 
			  PP_PROCESS_CONFIG = PPC
			  PP_PROCESS_CONFIG = PPC1
			  ADM_CODE_ELEMENTS = ACE
			
Relation : 	PPTP.PROD_PROC_TYPE_ID = PPPT.ID
            PPC.ID = PPTP.PROCESS_ID
            PPC1.ID = PPTP.SUB_PROCESS_ID
            ACE.ID = PPTP.WIP_STAGE_ID
			
Filter by:  WHERE PPTP.WIP_STAGE_ID = 7611
                  
QUERY :
   
SELECT PPTP.PROCESS_ID,PPC.PROCESS_NAME,PPTP.SUB_PROCESS_ID,PPC1.PROCESS_NAME AS SUB_PROCESS_NAME,PPTP.WIP_STAGE_ID,ACE.ELEMENT_NAME,
PPTP.IPQC_REQUIRED, PPTP.QC_REQUIRED, PPTP.RECONCILIATION_REQUIRED,PPTP.TOTAL_PROCESS_TIME,PPTP.IS_MACHINE_GROUP,PPTP.PROCESS_SEQUENCE
FROM PP_PROD_PROC_TYPE PPPT
LEFT JOIN PP_PROC_TYPE_PROCESS  PPTP ON PPTP.PROD_PROC_TYPE_ID = PPPT.ID
LEFT JOIN PP_PROCESS_CONFIG PPC ON PPC.ID = PPTP.PROCESS_ID
LEFT JOIN PP_PROCESS_CONFIG PPC1 ON PPC1.ID = PPTP.SUB_PROCESS_ID
LEFT JOIN ADM_CODE_ELEMENTS ACE ON ACE.ID = PPTP.WIP_STAGE_ID
WHERE PPPT.PROD_ID = :pPROD_ID --4001
AND PPPT.SBU_ID = :pSBU_ID --2
AND PPTP.WIP_STAGE_ID = 7611 -- WIP-BULK AND 7622 -- WIP-SEMI-FINISHED
GROUP BY PPTP.PROCESS_ID,PPC.PROCESS_NAME,PPTP.SUB_PROCESS_ID,PPC1.PROCESS_NAME,PPTP.WIP_STAGE_ID,ACE.ELEMENT_NAME,
PPTP.IPQC_REQUIRED, PPTP.QC_REQUIRED, PPTP.RECONCILIATION_REQUIRED,PPTP.TOTAL_PROCESS_TIME,PPTP.IS_MACHINE_GROUP,PPTP.PROCESS_SEQUENCE
ORDER BY PPTP.PROCESS_SEQUENCE;

----------------------------------------------------------


GET BPR PROCESS INFO DATA  
API TYPE : GET
API NAME : api/pp/get-bpr-process-data

Response Fields :  

        PPTP.PROCESS_ID,PPC.PROCESS_NAME,PPTP.SUB_PROCESS_ID,PPC1.PROCESS_NAME AS SUB_PROCESS_NAME,PPTP.WIP_STAGE_ID,ACE.ELEMENT_NAME,
        PPTP.IPQC_REQUIRED, PPTP.QC_REQUIRED, PPTP.RECONCILIATION_REQUIRED,PPTP.TOTAL_PROCESS_TIME,PPTP.IS_MACHINE_GROUP,PPTP.PROCESS_SEQUENCE
	  
Operational Fields: 
		PPTP.PROCESS_ID,PPC.PROCESS_NAME,PPTP.SUB_PROCESS_ID,PPC1.PROCESS_NAME AS SUB_PROCESS_NAME,PPTP.WIP_STAGE_ID,ACE.ELEMENT_NAME,
        PPTP.IPQC_REQUIRED, PPTP.QC_REQUIRED, PPTP.RECONCILIATION_REQUIRED,PPTP.TOTAL_PROCESS_TIME,PPTP.IS_MACHINE_GROUP,PPTP.PROCESS_SEQUENCE
         
PARAMETER  : WHERE PPPT.PROD_ID = :pPROD_ID 
             AND PPPT.SBU_ID = :pSBU_ID

Table Name:   PP_PROD_PROC_TYPE = PPPT
			  PP_PROC_TYPE_PROCESS  = PPTP 
			  PP_PROCESS_CONFIG = PPC
			  PP_PROCESS_CONFIG = PPC1
			  ADM_CODE_ELEMENTS = ACE
			
Relation : 	PPTP.PROD_PROC_TYPE_ID = PPPT.ID
            PPC.ID = PPTP.PROCESS_ID
            PPC1.ID = PPTP.SUB_PROCESS_ID
            ACE.ID = PPTP.WIP_STAGE_ID
			
Filter by:  WHERE PPTP.WIP_STAGE_ID = 7612
                  
QUERY :
   
SELECT PPTP.PROCESS_ID,PPC.PROCESS_NAME,PPTP.SUB_PROCESS_ID,PPC1.PROCESS_NAME AS SUB_PROCESS_NAME,PPTP.WIP_STAGE_ID,ACE.ELEMENT_NAME,
PPTP.IPQC_REQUIRED, PPTP.QC_REQUIRED, PPTP.RECONCILIATION_REQUIRED,PPTP.TOTAL_PROCESS_TIME,PPTP.IS_MACHINE_GROUP,PPTP.PROCESS_SEQUENCE
FROM PP_PROD_PROC_TYPE PPPT
LEFT JOIN PP_PROC_TYPE_PROCESS  PPTP ON PPTP.PROD_PROC_TYPE_ID = PPPT.ID
LEFT JOIN PP_PROCESS_CONFIG PPC ON PPC.ID = PPTP.PROCESS_ID
LEFT JOIN PP_PROCESS_CONFIG PPC1 ON PPC1.ID = PPTP.SUB_PROCESS_ID
LEFT JOIN ADM_CODE_ELEMENTS ACE ON ACE.ID = PPTP.WIP_STAGE_ID
WHERE PPPT.PROD_ID = :pPROD_ID --191
AND PPPT.SBU_ID = :pSBU_ID --2
AND PPTP.WIP_STAGE_ID = 7612 -- WIP-BULK AND 7612 -- WIP-SEMI-FINISHED
GROUP BY PPTP.PROCESS_ID,PPC.PROCESS_NAME,PPTP.SUB_PROCESS_ID,PPC1.PROCESS_NAME,PPTP.WIP_STAGE_ID,ACE.ELEMENT_NAME,
PPTP.IPQC_REQUIRED, PPTP.QC_REQUIRED, PPTP.RECONCILIATION_REQUIRED,PPTP.TOTAL_PROCESS_TIME,PPTP.IS_MACHINE_GROUP,PPTP.PROCESS_SEQUENCE
ORDER BY PPTP.PROCESS_SEQUENCE;