
MODAL- LANDING MODE RIGHT SIDE Clone From - 5th API
API TYPE : GET
API NAME : api/pp/get-version-list/pPROD_ID

Response Fields :  
                    PROD_ID,VERSION_NO
	  
Operational Fields: 
                PROD_ID,VERSION_NO
         
PARAMETER  : 

Table Name:   	PP_RECEIPE_MST


Relation : 	  	
    
Filter by:  

QUERY : 
    
SELECT PROD_ID,VERSION_NO FROM PP_RECEIPE_MST
WHERE PROD_ID=:pPROD_ID --(come from 2nd api)

----------------------------------------

MODAL- LANDING MODE RIGHT SIDE Clone From - 6th API
API TYPE : GET
API NAME : api/pp/get-version-dtl/pPROD_ID/pVERSION_NO

Response Fields :  
                    MAT_PROD_ID, REQUIRED_QTY, REQUIRED_UOM, OVERAGE, TOTAL_WITH_WASTAGE_QTY, SPEC 
	  
Operational Fields: 
                MAT_PROD_ID, REQUIRED_QTY, REQUIRED_UOM, OVERAGE, TOTAL_WITH_WASTAGE_QTY, SPEC 
         
PARAMETER  :  PRM.PROD_ID = :pPROD_ID (come from 5th api)
              PRM.VERSION_NO = :pVERSION_NO (come from 5th api)

Table Name:   	PP_RECEIPE_DTL = PRD
                PP_RECEIPE_MST = PRM


Relation : 	   PRM.ID = PRD.RECEIPE_ID
    
Filter by:  

QUERY : 

SELECT MAT_PROD_ID,AP.PROD_NAME, REQUIRED_QTY, REQUIRED_UOM, OVERAGE, TOTAL_WITH_WASTAGE_QTY, SPEC 
FROM PP_RECEIPE_DTL PRD
LEFT JOIN PP_RECEIPE_MST PRM ON PRM.ID = PRD.RECEIPE_ID
LEFT JOIN ADM_PRODUCTS AP ON AP.ID = PRD.MAT_PROD_ID
WHERE PRM.PROD_ID = :pPROD_ID --(come from 5th api)
AND PRM.VERSION_NO = :pVERSION_NO --(come from 5th api)

---------------------------------------------------

LEFT PANEL- WHEN VERSION CLICK SHOW RIGHT SIDE MASTER DATA - 8th API
API TYPE : GET
API NAME : api/pp/get-version-wise-mst-data

Response Fields :
                PRM.ID,PROD_ID,AP.PROD_NAME, PROD_QTY, PROD_UOM,PROD_WEIGHT,WEIGHT_UOM,VERSION_NO,STATUS

Operational Fields :
                   PRM.ID,PROD_ID,AP.PROD_NAME, PROD_QTY, PROD_UOM,PROD_WEIGHT,WEIGHT_UOM,DISPLAY_CODE,
                   VERSION_NO, TRAN_STATUS,STATUS

PARAMETER : PRM.PROD_ID = :pPROD_ID  --(come from 1no api )
            PRM.VERSION_NO = :pVERSION_NO  --(come from 1no api )

Table Name:  PP_RECEIPE_MST = PRM
            ADM_PRODUCTS = AP
            
Relation :  AP.ID = PRM.PROD_ID
            ACE.ID = PRM.TRAN_STATUS
         

Special Condition: 

INSTRUCTION:

QUERY :

SELECT PRM.ID,PROD_ID,AP.PROD_NAME, PROD_QTY, PROD_UOM,PROD_WEIGHT,WEIGHT_UOM,DISPLAY_CODE,VERSION_NO, TRAN_STATUS,
DECODE(PRM.STATUS,1,'ACTIVE','INACTIVE') STATUS
FROM PP_RECEIPE_MST PRM
LEFT JOIN ADM_PRODUCTS AP ON AP.ID = PRM.PROD_ID
WHERE PRM.PROD_ID = :pPROD_ID 
AND PRM.VERSION_NO = :pVERSION_NO 

-------------------------------------------------------

LEFT PANEL- WHEN VERSION CLICK SHOW RIGHT SIDE DETAILS DATA - 8th API
API TYPE : GET
API NAME : api/pp/get-version-wise-mst-data

Response Fields :
                PRD.MAT_PROD_ID,AP.PROD_NAME, PRD.REQUIRED_QTY, PRD.REQUIRED_UOM, PRD.OVERAGE, PRD.TOTAL_WITH_WASTAGE_QTY, PRD.SPEC

Operational Fields :
                   PRD.ID RECP_DTL_ID,PRD.MAT_PROD_ID,AP.PROD_NAME, PRD.REQUIRED_QTY, PRD.REQUIRED_UOM, PRD.OVERAGE, PRD.TOTAL_WITH_WASTAGE_QTY, PRD.SPEC

PARAMETER : PRM.PROD_ID = :pPROD_ID  --(come from 1no api )
            PRM.VERSION_NO = :pVERSION_NO  --(come from 1no api )

Table Name:  PP_RECEIPE_MST = PRM
             PP_RECEIPE_DTL = PRD
             ADM_PRODUCTS = AP
            
Relation :  PRM.ID = PRD.RECEIPE_ID
            AP.ID = PRD.MAT_PROD_ID
         

Special Condition: 

INSTRUCTION:

QUERY :

SELECT PRD.ID RECP_DTL_ID,PRD.MAT_PROD_ID,AP.PROD_NAME, PRD.REQUIRED_QTY, PRD.REQUIRED_UOM, 
PRD.OVERAGE, PRD.TOTAL_WITH_WASTAGE_QTY, PRD.SPEC,APC.CAT_NAME AS PROD_CAT_NAME
FROM PP_RECEIPE_DTL PRD
LEFT JOIN PP_RECEIPE_MST PRM ON PRM.ID = PRD.RECEIPE_ID
LEFT JOIN ADM_PRODUCTS AP ON AP.ID = PRD.MAT_PROD_ID
LEFT JOIN ADM_PROD_CATEGORY APC ON AP.PROD_CAT = APC.ID
WHERE PRM.PROD_ID = :pPROD_ID 
AND PRM.VERSION_NO = :pVERSION_NO


---------------1NO API-------------------------

SELECT A.RECEIPE_ID,A.PROD_ID,A.PROD_NAME,A.VERSION_NO,B.VERSION_NO CURRENT_VERSION, B.PROD_QTY,B.PROD_UOM,PUOM.ELEMENT_NAME AS UOM_NAME,
B.PROD_WEIGHT, B.WEIGHT_UOM,WUOM.ELEMENT_NAME AS WEGT_UOM_NAME,DECODE(B.STATUS,1,'ACTIVE','INACTIVE') STATUS,SEARCH_KEYWORD,
B.TRAN_STATUS,TS.ELEMENT_NAME
FROM (
SELECT PROD_ID,AP.PROD_NAME,LISTAGG(PRM.VERSION_NO,',') WITHIN GROUP(ORDER BY PRM.VERSION_NO) VERSION_NO,
(SELECT ID FROM PP_RECEIPE_MST WHERE PROD_ID=PRM.PROD_ID AND STATUS=1 ORDER BY ID ASC FETCH  FIRST ROW ONLY) RECEIPE_ID 
FROM PP_RECEIPE_MST PRM
JOIN ADM_PRODUCTS AP ON AP.ID = PRM.PROD_ID
GROUP BY PROD_ID,AP.PROD_NAME)A
LEFT JOIN PP_RECEIPE_MST B ON A.RECEIPE_ID=B.ID
LEFT JOIN ADM_CODE_ELEMENTS PUOM ON B.PROD_UOM=PUOM.ID
LEFT JOIN ADM_CODE_ELEMENTS WUOM ON WUOM.ID = B.WEIGHT_UOM
LEFT JOIN ADM_CODE_ELEMENTS TS ON B.TRAN_STATUS=TS.ID



--------------
SELECT PROD_ID,AP.PROD_NAME,LISTAGG(PRM.VERSION_NO,',') WITHIN GROUP(ORDER BY PRM.VERSION_NO) VERSION_NO,
(SELECT ID FROM PP_RECEIPE_MST WHERE PROD_ID=PRM.PROD_ID AND STATUS=1 ORDER BY ID ASC FETCH  FIRST ROW ONLY) RECEIPE_ID
FROM PP_RECEIPE_MST PRM
LEFT JOIN ADM_PRODUCTS AP ON AP.ID = PRM.PROD_ID
GROUP BY PROD_ID,AP.PROD_NAME